import { useState } from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import useBrokenLinks from '@docusaurus/useBrokenLinks';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import { Highlight, themes } from 'prism-react-renderer';

import sample from '../data/generated.json';
import styles from './index.module.css';

// Everything below comes from website/sample, compiled for real: npm run generate-sample rebuilds it.
const order = sample.inputs.find((file) => file.name === 'Order.cs');
const heroCode = order.code.slice(order.code.indexOf('[AggregateRoot'));
const written = sample.inputs.reduce((sum, file) => sum + file.lines, 0);
const generatedLines = sample.files.reduce((sum, file) => sum + file.lines, 0);
// The shadow behind the hero starts with what Order.cs itself produced. It shows the code, so the
// compiler headers and XML documentation are left out there; the explorer below shows every line.
const shadowFirst = ['Order.g.cs', 'OrderId.g.cs', 'Address.g.cs', 'OrderLine.g.cs'];
const shadowRank = (file) => (shadowFirst.includes(file.name) ? shadowFirst.indexOf(file.name) : shadowFirst.length);
const shadowCode = [...sample.files]
  .sort((a, b) => shadowRank(a) - shadowRank(b))
  .map((file) => `// ${file.name}\n${file.code.replace(/^(\/\/ <auto-generated\/>|#nullable enable|#pragma warning disable .*|\s*\/\/\/.*)\n/gm, '').trim()}`)
  .join('\n\n');

// What each file is for, in words a reader who has never seen the toolkit can follow.
const explanations = {
  'Order.cs':
    'The aggregate as you write it. The attribute is the whole declaration: the base class, the id type and the persistence plumbing are the generator’s job.',
  'OrderLine.cs': 'A child entity of the order. It is saved and loaded with its order, and has an id of its own.',
  'Address.cs': 'A value object: two addresses with the same street and city are the same address.',
  'OrderPlaced.cs': 'A domain event the order raises. The name is what gets stored, so renaming the class breaks nothing.',
  'Order.g.cs':
    'Order’s base class, AggregateRoot<OrderId>, and the constructor Entity Framework needs. The invariant check that runs MustHaveLines before every save. And the list behind Lines: inside Order you add to _lines, outside it callers can only read.',
  'OrderId.g.cs':
    'The OrderId the attribute asked for: a struct around a Guid, printed as ORD_…, with Parse, comparison and a JSON converter.',
  'OrderLine.g.cs':
    'The same for the line: its base class, its Entity Framework constructor and its own invariant check, which Order runs for every line.',
  'OrderLineId.g.cs': 'The id of a line, printed as LINE_…. Nobody wrote an OrderLineId file: the attribute on OrderLine was enough.',
  'Address.g.cs':
    'Equality over Street and City, a With() that copies with changes, and ValidAddress: a twin type that can only exist when the address is valid.',
  'Address.EntityFramework.g.cs': 'Maps Address as an EF Core complex type, so its fields become columns of the table it is stored in.',
  'ConverterExtensions.g.cs': 'AddShopConverters(): one call in ConfigureConventions and every id is stored as its plain value.',
  'EventNames.g.cs':
    'ShopEventNames.OrderPlaced: every name an event is stored or published under, as a constant, so a topic binding or a test never spells one out by hand.',
  'IntegrationEventExtensions.g.cs':
    'AddShopIntegrationEvents(): registers OrderPlaced with the outbox under its stored name, without scanning an assembly at start-up.',
  'OrderId.Converter.g.cs': 'Stores an OrderId as a plain uuid column and reads it back as an OrderId.',
  'OrderLine.EntityFramework.g.cs': 'Maps the lines as owned by their order: saved in the same transaction, never on their own.',
  'OrderLineId.Converter.g.cs': 'The same converter for the line’s id.',
  'BindingExtensions.g.cs': 'AddShopGraphQlRuntimeBindings(): ids appear in the schema as UUID scalars and inside Relay node ids.',
  'OrderId.HotChocolate.g.cs': 'Converts OrderId for HotChocolate, and writes it into and reads it out of a Relay node id.',
  'OrderLineId.HotChocolate.g.cs': 'The same for the line’s id.',
};

const reasons = [
  {
    title: 'Plain C#, in your project',
    text: 'The output is ordinary C# added to your compilation. Go to definition opens it and the debugger steps through it. Nothing is woven into IL or built at run time.',
    icon: 'M8 6l-6 6 6 6M16 6l6 6-6 6',
  },
  {
    title: 'Never out of step',
    text: 'Add a property to a value object and its equality, its With() and its database mapping follow at the next build. There is no second file to forget.',
    icon: 'M4 12a8 8 0 0114-5.3L20 9M20 4v5h-5M20 12a8 8 0 01-14 5.3L4 15M4 20v-5h5',
  },
  {
    title: 'Mistakes are compile errors',
    text: 'An invariant declared where it would never run, or a module reaching into another one’s internals, is a diagnostic in your editor instead of a bug in production.',
    icon: 'M12 3l9 16H3l9-16zM12 10v4M12 17h.01',
    to: '/docs/diagnostics',
  },
  {
    title: 'No reflection in the hot path',
    text: 'Equality, id conversions and invariant checks call your members directly. A struct id costs what the Guid inside it costs, and the benchmarks show it.',
    icon: 'M13 3L4 14h7l-1 7 9-11h-7l1-7z',
    to: '/docs/performance',
  },
  {
    title: 'Only what you use',
    text: 'An entity without rules gets no rule list and no check to run. What you do not need is not generated, so it costs nothing at all.',
    icon: 'M4 6h16M7 12h10M10 18h4',
  },
  {
    title: 'One declaration, every integration',
    text: 'Reference the Entity Framework or HotChocolate package and the same attribute also brings value converters, GraphQL scalars and Relay node ids.',
    icon: 'M12 3v6M12 15v6M3 12h6M15 12h6M12 9a3 3 0 110 6 3 3 0 010-6z',
  },
];

const blocks = [
  {
    title: 'Identifiers',
    to: '/docs/identifiers',
    text: 'Typed ids from one attribute: no primitive obsession, no hand-written converters for EF, JSON or GraphQL.',
    icon: 'M4 7h16M4 12h10M4 17h7M18 14l3 3-3 3',
  },
  {
    title: 'Value objects',
    to: '/docs/value-objects',
    text: 'Structural equality, validation that names what is wrong, and an always-valid twin the compiler keeps honest.',
    icon: 'M12 3l8 4.5v9L12 21l-8-4.5v-9L12 3zM12 12l8-4.5M12 12v9M12 12L4 7.5',
  },
  {
    title: 'Aggregates and invariants',
    to: '/docs/invariants',
    text: 'Rules as named classes inside the aggregate, run before every save, with a code a client can act on.',
    icon: 'M12 3l7 4v5c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V7l7-4zM9 12l2 2 4-4',
  },
  {
    title: 'Domain events',
    to: '/docs/domain-events',
    text: 'Raised by the aggregate, dispatched with the save, stable names that survive a rename.',
    icon: 'M13 3L4 14h7l-1 7 9-11h-7l1-7z',
  },
  {
    title: 'Modules and integration events',
    to: '/docs/modules',
    text: 'Boundaries the analyzers enforce, an outbox and an inbox per module, contracts that version.',
    icon: 'M4 4h7v7H4zM13 13h7v7h-7zM11 7.5h4.5V13M13 16.5H8.5V11',
  },
  {
    title: 'GraphQL',
    to: '/docs/graphql',
    text: 'Ids as scalars and Relay node ids, rules as errors with codes, one schema over the modules with Fusion.',
    icon: 'M12 3l7.8 4.5v9L12 21l-7.8-4.5v-9L12 3zM12 3v18M4.2 7.5l15.6 9M19.8 7.5l-15.6 9',
  },
];

const packages = [
  ['DDDToolkit', 'Base types and the core generators.'],
  ['DDDToolkit.EntityFramework', 'Mapping, conventions, event dispatch, the outbox and the inbox.'],
  ['DDDToolkit.EntityFramework.Postgres', 'Row level security, and rules in C# as Postgres policies.'],
  ['DDDToolkit.EntityFramework.Supabase', 'Migrations and policies exported for supabase db push and branching.'],
  ['DDDToolkit.Auth.Supabase', 'Supabase Auth, and each token’s user as the caller.'],
  ['DDDToolkit.Auth.Supabase.AspNetCore', 'The same for ASP.NET Core requests.'],
  ['DDDToolkit.Auth.Supabase.AzureFunctions', 'The same for Azure Functions invocations.'],
  ['DDDToolkit.HotChocolate', 'GraphQL bindings, node ids, errors with codes, subscriptions.'],
  ['DDDToolkit.HotChocolate.Fusion.InMemory', 'One schema over a modular monolith, composed in process.'],
  ['DDDToolkit.Messaging.Postgres', 'pgmq: a queue in the database the outbox already writes to.'],
  ['DDDToolkit.Messaging.Wolverine', 'Wolverine as the transport between outbox and inbox.'],
  ['DDDToolkit.Messaging.MassTransit', 'MassTransit 8 as that transport.'],
  ['DDDToolkit.Mediator', 'Domain events dispatched through Mediator.'],
  ['DDDToolkit.FluentValidation', 'A generated validator per value object.'],
  ['DDDToolkit.Localization', 'Failures phrased in the reader’s language.'],
  ['DDDToolkit.Testing', 'Given/when/then tests for the domain events an aggregate raises.'],
];

const hosts = [
  { name: 'Modular monolith', detail: 'Supabase or SQL Server', transport: 'in process' },
  { name: 'Services over pgmq', detail: 'one Postgres, a queue per service', transport: 'pgmq' },
  { name: 'Services over RabbitMQ', detail: 'a database per service', transport: 'Wolverine' },
  { name: 'Services over RabbitMQ', detail: 'SQL Server per service', transport: 'MassTransit' },
];

function Icon({ d }) {
  return (
    <svg className={styles.icon} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d={d} />
    </svg>
  );
}

// One Dark in both colour modes: the code windows are dark whatever the page is.
function Code({ code, className }) {
  return (
    <Highlight theme={themes.oneDark} code={code} language="csharp">
      {({ tokens, getLineProps, getTokenProps }) => (
        <pre className={clsx(styles.code, className)}>
          {tokens.map((line, i) => (
            <div key={i} {...getLineProps({ line })}>
              {line.map((token, key) => (
                <span key={key} {...getTokenProps({ token })} />
              ))}
            </div>
          ))}
        </pre>
      )}
    </Highlight>
  );
}

function Window({ title, children, className }) {
  return (
    <div className={clsx(styles.window, className)}>
      <div className={styles.windowBar}>
        <span />
        <span />
        <span />
        <em>{title}</em>
      </div>
      {children}
    </div>
  );
}

function Hero() {
  return (
    <header className={styles.hero}>
      <div className={styles.heroGlow} aria-hidden="true" />
      <div className={clsx('container', styles.heroInner)}>
        <div className={styles.heroText}>
          <img className={styles.heroLogo} src={useBaseUrl('/img/logo.svg')} alt="" />
          <span className={styles.badge}>Roslyn source generators for .NET 10</span>
          <Heading as="h1" className={styles.heroTitle}>
            You write the domain.
            <br />
            <span className={styles.gradientText}>The compiler writes the rest.</span>
          </Heading>
          <p className={styles.heroLead}>
            Declare an aggregate, a value object or an identifier with one attribute. At compile time DDDToolkit generates the base
            types, equality, invariant checks, Entity Framework mapping and GraphQL bindings, as plain C# you can open, read and
            step through.
          </p>
          <div className={styles.install}>
            <span className={styles.prompt}>$</span>
            <code>dotnet add package DDDToolkit</code>
          </div>
          <div className={styles.buttons}>
            <Link className={clsx('button button--lg', styles.primaryButton)} to="/docs/getting-started">
              Get started
            </Link>
            <Link className={clsx('button button--lg', styles.secondaryButton)} href="#generated">
              See what it generates
            </Link>
          </div>
        </div>
        <div className={styles.heroCode}>
          <div className={styles.shadow} aria-hidden="true">
            <Window title={`Generated by the compiler · ${sample.files.length} files, ${generatedLines} lines`} className={styles.shadowWindow}>
              <div className={styles.shadowScroll}>
                <Code code={shadowCode} />
                <Code code={shadowCode} />
              </div>
            </Window>
          </div>
          <Window title="Order.cs" className={styles.frontWindow}>
            <Code code={heroCode} />
          </Window>
          <a className={styles.generatedChip} href="#generated">
            <strong>{written}</strong> lines written <span>→</span> <strong>{generatedLines.toLocaleString('en')}</strong> lines
            generated
          </a>
        </div>
      </div>
    </header>
  );
}

function Why() {
  return (
    <section className={styles.section}>
      <div className="container">
        <p className={styles.eyebrow}>Why a source generator</p>
        <Heading as="h2" className={styles.sectionTitle}>
          The boilerplate is real code. Nobody should have to write it.
        </Heading>
        <p className={styles.sectionLead}>
          Typed ids, equality, invariant checks and mappings are where a DDD code base spends its lines, and where it drifts. A
          generator writes them at compile time from what you declared, so they are there, correct and current, without a runtime
          library guessing at your types.
        </p>
        <div className={styles.cardGrid}>
          {reasons.map((reason) => {
            const content = (
              <>
                <Icon d={reason.icon} />
                <Heading as="h3">{reason.title}</Heading>
                <p>{reason.text}</p>
                {reason.to && <span className={styles.cardMore}>Read more →</span>}
              </>
            );
            return reason.to ? (
              <Link key={reason.title} to={reason.to} className={styles.card}>
                {content}
              </Link>
            ) : (
              <div key={reason.title} className={clsx(styles.card, styles.cardStatic)}>
                {content}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

function FileButton({ file, active, onSelect }) {
  return (
    <button type="button" className={clsx(styles.file, active && styles.fileActive)} onClick={() => onSelect(file)}>
      <span>{file.name}</span>
      <small>{file.lines}</small>
    </button>
  );
}

function Explorer() {
  const [selected, setSelected] = useState(() => sample.files.find((file) => file.name === 'Order.g.cs'));
  const generators = [...new Set(sample.files.map((file) => file.package))];
  // The hero links here; registering the anchor is what lets the build check that link.
  useBrokenLinks().collectAnchor('generated');

  return (
    <section id="generated" className={clsx(styles.section, styles.band)}>
      <div className="container">
        <p className={styles.eyebrow}>What gets generated</p>
        <Heading as="h2" className={styles.sectionTitle}>
          {written} lines in, {generatedLines.toLocaleString('en')} lines out
        </Heading>
        <p className={styles.sectionLead}>
          An order, its lines, an address and one event. Pick a file to see what the generators wrote for it. This is their real
          output for these four files, with only the <code>global::</code> prefixes taken out.
        </p>
        <div className={styles.explorer}>
          <nav className={styles.files} aria-label="Files">
            <p className={styles.filesHeading}>You write</p>
            {sample.inputs.map((file) => (
              <FileButton key={file.name} file={file} active={selected === file} onSelect={setSelected} />
            ))}
            {generators.map((name) => (
              <div key={name}>
                <p className={styles.filesHeading}>
                  Generated by <code>{name}</code>
                </p>
                {sample.files
                  .filter((file) => file.package === name)
                  .map((file) => (
                    <FileButton key={file.name} file={file} active={selected === file} onSelect={setSelected} />
                  ))}
              </div>
            ))}
          </nav>
          <div className={styles.viewer}>
            <p className={styles.explanation}>{explanations[selected.name]}</p>
            <Window title={`${selected.name} · ${selected.lines} lines`} className={styles.viewerWindow}>
              <Code code={selected.code} className={styles.viewerCode} />
            </Window>
          </div>
        </div>
        <p className={styles.explorerFoot}>
          See it in your own project with go to definition on any generated member, or on disk with{' '}
          <code>EmitCompilerGeneratedFiles</code>. <Link to="/docs/generated-code">What each attribute generates →</Link>
        </p>
      </div>
    </section>
  );
}

function Blocks() {
  return (
    <section className={styles.section}>
      <div className="container">
        <Heading as="h2" className={styles.sectionTitle}>
          The building blocks
        </Heading>
        <p className={styles.sectionLead}>Everything a DDD code base writes by hand, declared once and checked at compile time.</p>
        <div className={styles.cardGrid}>
          {blocks.map((block) => (
            <Link key={block.title} to={block.to} className={styles.card}>
              <Icon d={block.icon} />
              <Heading as="h3">{block.title}</Heading>
              <p>{block.text}</p>
              <span className={styles.cardMore}>Read more →</span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}

function Hosts() {
  return (
    <section className={clsx(styles.section, styles.band)}>
      <div className="container">
        <div className="row">
          <div className="col col--5">
            <Heading as="h2" className={styles.sectionTitle}>
              One domain, hosted any way you like
            </Heading>
            <p className={styles.sectionLead}>
              The example is a shop in five modules: Catalog, Ordering, Inventory, Payments and Shipping. The same modules run as
              one monolith and as three services, over four transports, and the same checkout scenarios pass against every one.
            </p>
            <Link className={clsx('button', styles.secondaryButton)} href="https://github.com/DylanSnel/DDDToolkit/tree/main/Examples">
              See the samples
            </Link>
          </div>
          <div className="col col--7">
            <div className={styles.hostList}>
              {hosts.map((host) => (
                <div key={host.transport} className={styles.host}>
                  <div>
                    <strong>{host.name}</strong>
                    <span>{host.detail}</span>
                  </div>
                  <span className={styles.transport}>{host.transport}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Packages() {
  return (
    <section className={styles.section}>
      <div className="container">
        <Heading as="h2" className={styles.sectionTitle}>
          Take only what you use
        </Heading>
        <p className={styles.sectionLead}>A core package and an integration per tool, each on NuGet.</p>
        <div className={styles.packageGrid}>
          {packages.map(([name, text]) => (
            <a key={name} className={styles.package} href={`https://www.nuget.org/packages/${name}`}>
              <code>{name}</code>
              <span>{text}</span>
            </a>
          ))}
        </div>
      </div>
    </section>
  );
}

function CallToAction() {
  return (
    <section className={styles.cta}>
      <div className="container">
        <Heading as="h2">Write the domain. Let the compiler write the rest.</Heading>
        <Link className={clsx('button button--lg', styles.ctaButton)} to="/docs/getting-started">
          Start with the guide
        </Link>
      </div>
    </section>
  );
}

export default function Home() {
  return (
    <Layout
      title="Domain-Driven Design for .NET"
      description="Domain-Driven Design for .NET, source generated: you write the domain and the compiler writes the boilerplate.">
      <Hero />
      <main>
        <Why />
        <Explorer />
        <Blocks />
        <Hosts />
        <Packages />
        <CallToAction />
      </main>
    </Layout>
  );
}
