using DDDToolkit.Abstractions.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGeneratorsToolkit.Providers;
using SourceGeneratorsToolkit.Providers.Contexts;
using SourceGeneratorsToolkit.SyntaxExtensions;
using System.Text;

namespace DDDToolkit.EntityFramework.Analyzers.Generators;

[Generator]
public class EntityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //#if DEBUG
        //        if (!System.Diagnostics.Debugger.IsAttached)
        //        {

        //            System.Diagnostics.Debugger.Launch();
        //        }
        //#endif

        var singleValueObjects = context.FindAttributesProvider<EntityAttribute, ClassDeclarationSyntax>();
        context.RegisterSourceOutput(singleValueObjects, Execute);
    }

    private static void Execute(SourceProductionContext context, ResultTypeAttributeSyntaxContext data)
    {
        var recordDeclaration = data.TargetNode as ClassDeclarationSyntax;
        if (recordDeclaration is null)
        {
            return;
        }
        var name = recordDeclaration.GetName();
        var @namespace = recordDeclaration.GetNamespace();


        var sourceCode = $$$"""
                            // <auto-generated/>
                            using Microsoft.EntityFrameworkCore;

                            namespace {{{@namespace}}};

                            [Owned]
                            partial class {{{name}}}
                            {
                            }

                            [Owned]
                            partial class Valid{{{name}}}
                            {
                            }
    
                            """;
        // Add the generated source to the compilation
        context.AddSource($"{@namespace}.{name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }

}
