using DDDToolkit.Abstractions.Attributes;
using DDDToolkit.Analyzers.Common;
using DDDToolkit.Analyzers.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGeneratorsToolkit.Providers;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DDDToolkit.EntityFramework.Analyzers.Generators;

[Generator]
public class SingleValueObjectConverterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {

        //#if DEBUG
        //        if (!System.Diagnostics.Debugger.IsAttached)
        //        {
        //            System.Diagnostics.Debugger.Launch();
        //        }
        //#endif

        var dddPropteriesProvider = context.DDDOptionsProvider();


        var singleValueObjectSyntax = context.FindAttributesProvider<SingleValueObjectAttribute, RecordDeclarationSyntax>();
        var entityIdSyntax = context.FindAttributesProvider<EntityIdAttribute, RecordDeclarationSyntax>();

        var typeDeclarations = singleValueObjectSyntax.Collect().Combine(entityIdSyntax.Collect()).SelectMany((x, y) => x.Left.Concat(x.Right));

        var singleValueObjects = typeDeclarations.Select((ctx, _) => GenericObjectDefinition.FromTypeDeclarationSyntax(ctx));


        context.RegisterSourceOutput(singleValueObjects, GenerateValueConverter);

        var classesWithProperties = dddPropteriesProvider.Combine(singleValueObjects.Collect());
        var classesWithPropertiesAndCompilation = classesWithProperties.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(classesWithPropertiesAndCompilation, GenerateConfigurationExtensions);
    }
    private static void GenerateValueConverter(SourceProductionContext context, GenericObjectDefinition data)
    {
        var converterName = $"{data.Name}Converter";

        var sourceCode = $$$"""
                            // <auto-generated/>
                            using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

                            namespace {{{data.Namespace}}};
    
                            partial record {{{data.Name}}} 
                            {
                                public class {{{converterName}}} : ValueConverter<{{{data.Name}}}, {{{data.Type}}}>
                                {
                                    public {{{converterName}}}()
                                        : base(
                                            v => v.Value,
                                            v => new {{{data.Name}}}(v))
                                    {
                                    }
                                }
                            }
                            """;

        context.AddSource($"{data.Namespace}.{converterName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }



    private static void GenerateConfigurationExtensions(SourceProductionContext sourceContext, ((DDDOptions Properties, ImmutableArray<GenericObjectDefinition> records) data, Compilation compilation) context)
    {
        var records = context.data.records;
        var properties = context.data.Properties;
        var compilation = context.compilation;
        if (records.Length == 0)
        {
            return;
        }

        var distinctNamespaces = records.Select(c => c.Namespace).Distinct();
        var assemblyName = compilation.AssemblyName;
        var moduleName = properties.ModuleName;

        if (string.IsNullOrEmpty(moduleName))
        {
            moduleName = CreateModuleName(assemblyName);
        }
        var usingStatements = string.Join("\n", distinctNamespaces.Select(ns => $"using {ns};"));
        var propertiesConfigurations = string.Join("\n        ", records.Select(c => $"modelConfigurationBuilder.Properties<{c.Name}>().HaveConversion<{c.Name}.{c.Name}Converter>(){AddMaxlenght(c)};"));

        var sourceCode = $$"""
            // <auto-generated/>
            {{usingStatements}}
            using Microsoft.EntityFrameworkCore;

            namespace {{assemblyName}}.Converters;
            
            public static class ConverterExtensions
            {
                public static void Add{{moduleName}}Converters(this ModelConfigurationBuilder modelConfigurationBuilder)
                {
                    {{propertiesConfigurations}}
                }
            }
            """;

        sourceContext.AddSource("ConverterExtensions.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }

    private static string AddMaxlenght(GenericObjectDefinition record)
    {
        if ((record.Arguments?.TryGetValue("ColumnLength", out var value) ?? false) && ((int)value.Value! > -1))
        {
            return $".HaveMaxLength({value.Value})";
        }
        return "";
    }

    private static string CreateModuleName(string? assemblyName)
        => assemblyName is null
            ? "AssemblyTypes"
            : assemblyName.Replace(".", string.Empty);
}
