using System;
using System.Collections.Generic;

namespace DDDToolkit.Analyzers.Common;

/// <summary>Pieces of generated code shared by all emitters.</summary>
internal static class Emit
{
    /// <summary>Standard header: auto-generated marker, nullable context and the warnings generated code may trip.</summary>
    public static CodeWriter Header(this CodeWriter writer)
    {
        writer.Directive("// <auto-generated/>");
        writer.Directive("#nullable enable");
        writer.Directive("#pragma warning disable CS1591, CS8618, CS8669");
        writer.Line();
        return writer;
    }

    /// <summary>
    /// Enters the type's namespace and containing types. Dispose the result to close the containing
    /// types again. Nested types are re-opened as partial declarations.
    /// </summary>
    public static IDisposable TypeScope(this CodeWriter writer, TypeDeclarationInfo type)
    {
        if (type.Namespace.Length > 0)
        {
            writer.Line("namespace " + type.Namespace + ";");
            writer.Line();
        }

        var closers = new Stack<IDisposable>();
        foreach (var header in type.ContainingTypeHeaders)
        {
            closers.Push(writer.Block(header));
        }

        return new Scope(closers);
    }

    /// <summary>The generated record-equality members used by the value object family (mirrors the historical output).</summary>
    public static void RecordEqualityMembers(CodeWriter writer, string typeName, bool hashCodeFromComponents)
    {
        using (writer.Block("public virtual bool Equals(" + typeName + "? other)"))
        {
            writer.Line("if (other is null)");
            writer.Line("{");
            writer.Line("    return false;");
            writer.Line("}");
            writer.Line();
            writer.Line("return global::System.Linq.Enumerable.SequenceEqual(GetEqualityComponents(), other.GetEqualityComponents());");
        }

        writer.Line();

        if (hashCodeFromComponents)
        {
            writer.Line("public override int GetHashCode()");
            writer.Line("    => global::System.Linq.Enumerable.Aggregate(");
            writer.Line("        global::System.Linq.Enumerable.Select(GetEqualityComponents(), static component => component?.GetHashCode() ?? 0),");
            writer.Line("        static (left, right) => left ^ right);");
        }
        else
        {
            writer.Line("public override int GetHashCode() => base.GetHashCode();");
        }
    }

    private sealed class Scope(Stack<IDisposable> closers) : IDisposable
    {
        public void Dispose()
        {
            while (closers.Count > 0)
            {
                closers.Pop().Dispose();
            }
        }
    }
}
