// <auto-generated />
using System;
using System.Collections.Generic;
using Examples.Tenancy.Inspections.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Examples.Tenancy.Inspections.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InspectionsContext))]
    partial class InspectionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inspections")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DDDToolkit.EntityFramework.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("InspectionsOutboxMessages", "inspections");
                });

            modelBuilder.Entity("Examples.Tenancy.Inspections.Domain.Aggregates.Inspections.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByIdentity")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedByKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ChangedBySeat")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByIdentity")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CreatedBySeat")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Days", "Examples.Tenancy.Inspections.Domain.Aggregates.Inspections.Inspection.Days#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("DaysFrom");

                            b1.Property<DateOnly>("Until")
                                .HasColumnType("date")
                                .HasColumnName("DaysUntil");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Inspections", "inspections");

                    b
                        .HasAnnotation("DDDToolkit:Tenancy:RecordsWhoChanged", true)
                        .HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });
#pragma warning restore 612, 618
        }
    }
}
