// <auto-generated />
using System;
using System.Collections.Generic;
using DDDToolkit.NugetApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DDDToolkit.NugetApi.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DDDToolkit.NugetApi.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DDDToolkit.NugetApi.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "DDDToolkit.NugetApi.Domain.UserAggregate.User.Name#PersonName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MiddleNames")
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DDDToolkit.NugetApi.Domain.UserAggregate.User", b =>
                {
                    b.OwnsMany("DDDToolkit.NugetApi.Domain.UserAggregate.Entities.Order", "Orders", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("PlacedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("Order");

                            b1.WithOwner("User")
                                .HasForeignKey("UserId");

                            b1.OwnsMany("DDDToolkit.NugetApi.Domain.ProductAggregate.ValueObjects.ProductId", "Products", b2 =>
                                {
                                    b2.Property<Guid>("OrderUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("OrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("Value")
                                        .HasColumnType("uuid");

                                    b2.HasKey("OrderUserId", "OrderId", "Id");

                                    b2.ToTable("ProductId");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderUserId", "OrderId");
                                });

                            b1.Navigation("Products");

                            b1.Navigation("User");
                        });

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
