// <auto-generated />
using System;
using Examples.Tenancy.Tenants.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Examples.Tenancy.Tenants.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenantsContext))]
    partial class TenantsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenancy")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DDDToolkit.EntityFramework.EventLog.EventLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActedById")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ActedByKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AggregateId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("TenantId", "RecordedAt");

                    b.ToTable("TenancyEventLog", "tenancy");

                    b
                        .HasAnnotation("DDDToolkit:AppendOnly", true)
                        .HasAnnotation("DDDToolkit:AppendOnly:RecordedAt", "RecordedAt")
                        .HasAnnotation("DDDToolkit:Tenancy:EventLog", false);
                });

            modelBuilder.Entity("DDDToolkit.EntityFramework.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("TenancyOutboxMessages", "tenancy");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.MoveReach<Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId>", b =>
                {
                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndsAt");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Key");

                    b.Property<bool>("OfCaller")
                        .HasColumnType("boolean")
                        .HasColumnName("OfCaller");

                    b.Property<Guid>("Parent")
                        .HasColumnType("uuid")
                        .HasColumnName("Parent");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("UnitId");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.OrganizationUnitPath<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId>", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("DescendantId");

                    b.HasIndex("TenantId");

                    b.ToTable("OrganizationUnitPaths", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.OrganizationUnitRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("OrganizationUnits", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.PlacementRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId>", b =>
                {
                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("SeatPlacements", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.RoleRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.RoleId>", b =>
                {
                    b.Property<string>("FromPack")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Keys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("Roles", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.SeatRight<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId, Examples.Tenancy.Tenants.Contracts.ValueObjects.RoleId>", b =>
                {
                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("SeatId", "UnitId", "RoleId", "Key");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("SeatId", "Key");

                    b.ToTable("SeatRights", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.SeatRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("Seats", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.InvitationOfDigestRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.InvitationId, Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId>", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("InvitationId");

                    b.Property<Guid?>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("IssuedBy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.SeatHolderRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId>", b =>
                {
                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("SeatId");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);

                    b.HasAnnotation("DDDToolkit:Tenancy:FunctionSchema", null);
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.TenancyAccessRevision<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId>", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId");

                    b.ToTable("TenancyAccessRevisions", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.TenancyInvitationDigest<Examples.Tenancy.Tenants.Contracts.ValueObjects.InvitationId, Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId>", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Digest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("InvitationId");

                    b.HasIndex("Digest")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("InvitationDigests", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.TenantAdministratorRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Tenants.Contracts.ValueObjects.RoleId>", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("SeatId");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.TenantToSweepRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId>", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Examples.Tenancy.Tenants.Domain.Aggregates.Invitations.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedAs")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GrantUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedAccount")
                        .HasColumnType("uuid");

                    b.Property<bool>("IssuedAsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IssuedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "State", "ExpiresAt");

                    b.ToTable("Invitations", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("Examples.Tenancy.Tenants.Domain.Aggregates.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Organizations", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "Id");
                });

            modelBuilder.Entity("Examples.Tenancy.Tenants.Domain.Aggregates.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FromPack")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<string[]>("Keys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasAnnotation("DDDToolkit:RefusesAs:Code", "tenancy.role-name-taken")
                        .HasAnnotation("DDDToolkit:RefusesAs:Kind", "Conflict")
                        .HasAnnotation("DDDToolkit:RefusesAs:Message", "The tenant has a role named {Name} already.");

                    b.ToTable("Roles", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("Examples.Tenancy.Tenants.Domain.Aggregates.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("Identity")
                        .HasColumnType("uuid");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Identity", "TenantId")
                        .IsUnique()
                        .HasAnnotation("DDDToolkit:RefusesAs:Code", "tenancy.identity-has-seat")
                        .HasAnnotation("DDDToolkit:RefusesAs:Kind", "Conflict")
                        .HasAnnotation("DDDToolkit:RefusesAs:Message", "This person has a seat in the tenant already.");

                    b.ToTable("Seats", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("Examples.Tenancy.Tenants.Domain.Aggregates.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasAnnotation("DDDToolkit:RefusesAs:Code", "tenancy.slug-taken")
                        .HasAnnotation("DDDToolkit:RefusesAs:Kind", "Conflict")
                        .HasAnnotation("DDDToolkit:RefusesAs:Message", "The slug {Slug} is in use by another tenant.");

                    b.ToTable("Tenants", "tenancy");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "Id");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.TenancyInvitationDigest<Examples.Tenancy.Tenants.Contracts.ValueObjects.InvitationId, Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId>", b =>
                {
                    b.HasOne("Examples.Tenancy.Tenants.Domain.Aggregates.Invitations.Invitation", null)
                        .WithOne()
                        .HasForeignKey("DDDToolkit.Supporting.Tenancy.EntityFramework.TenancyInvitationDigest<Examples.Tenancy.Tenants.Contracts.ValueObjects.InvitationId, Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId>", "InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Examples.Tenancy.Tenants.Domain.Aggregates.Organizations.Organization", b =>
                {
                    b.OwnsMany("Examples.Tenancy.Tenants.Domain.Aggregates.Organizations.Entities.OrganizationUnit", "Units", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("CostCentre")
                                .HasColumnType("text");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid?>("ParentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ParentId");

                            b1.HasIndex("TenantId");

                            b1.HasIndex(new[] { "TenantId" }, "IX_OrganizationUnits_TenantId_WhereRoot")
                                .IsUnique()
                                .HasDatabaseName("IX_OrganizationUnits_TenantId_WhereRoot")
                                .HasFilter("\"ParentId\" IS NULL")
                                .HasAnnotation("DDDToolkit:RefusesAs:Code", "tenancy.one-root")
                                .HasAnnotation("DDDToolkit:RefusesAs:Kind", "Conflict")
                                .HasAnnotation("DDDToolkit:RefusesAs:Message", "The tree has one root, no more and no fewer.");

                            b1.ToTable("OrganizationUnits", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Examples.Tenancy.Tenants.Domain.Aggregates.Seats.Seat", b =>
                {
                    b.OwnsMany("DDDToolkit.Supporting.Tenancy.Placement<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId, Examples.Tenancy.Tenants.Contracts.ValueObjects.RoleId>", "Placements", b1 =>
                        {
                            b1.Property<Guid>("SeatId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<DateTime>("PlacedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("PlacedBy")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("SeatId", "UnitId");

                            b1.HasIndex(new[] { "SeatId" }, "IX_SeatPlacements_SeatId_WherePrimary")
                                .IsUnique()
                                .HasDatabaseName("IX_SeatPlacements_SeatId_WherePrimary")
                                .HasFilter("\"IsPrimary\"")
                                .HasAnnotation("DDDToolkit:RefusesAs:Code", "tenancy.second-primary")
                                .HasAnnotation("DDDToolkit:RefusesAs:Kind", "Conflict")
                                .HasAnnotation("DDDToolkit:RefusesAs:Message", "Only one of a seat's placements can be primary.");

                            b1.ToTable("SeatPlacements", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("SeatId");

                            b1.OwnsMany("DDDToolkit.Supporting.Tenancy.RoleGrant<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Tenants.Contracts.ValueObjects.RoleId>", "Grants", b2 =>
                                {
                                    b2.Property<Guid>("SeatId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("UnitId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RoleId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("EndsAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid?>("GrantedBy")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Reason")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.Property<DateTime>("StartsAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("SeatId", "UnitId", "RoleId");

                                    b2.HasIndex("RoleId");

                                    b2.ToTable("SeatRoleGrants", "tenancy");

                                    b2.WithOwner()
                                        .HasForeignKey("SeatId", "UnitId");
                                });

                            b1.Navigation("Grants");
                        });

                    b.Navigation("Placements");
                });
#pragma warning restore 612, 618
        }
    }
}
