using DDDToolkit.HotChocolate;
using DDDToolkit.HotChocolate.Authorization;
using Examples.Hosting;
using Examples.Tenancy.Tenants.Api.Roles.GraphQL;
using Examples.Tenancy.Tenants.Api.GraphQl;
using Examples.Tenancy.Tenants.Api.Seats.GraphQL;
using Examples.Tenancy.Tenants.Application.Roles;
using HotChocolate.Execution.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Examples.Tenancy.Tenants.Api.GraphQL;

/// <summary>
/// Tenancy's GraphQL source schema: a schema of its own, which a gateway in the host composes with the other
/// modules' into the one schema a client sees.
/// </summary>
/// <remarks>
/// Tenancy owns what a seat, a unit and a role are called. The other modules name them by id alone, and the
/// gateway fetches the rest here, through the three lookups of the <c>Directory</c> feature. Each feature's
/// queries, mutations and types are in its own <c>GraphQL</c> folder, beside its routes; this class only puts
/// them together.
/// <para>
/// A type of the schema is declared over the record the application layer answers, in a type class beside the
/// fields that answer it, so no record is copied for the schema's sake. HotChocolate's generator registers the
/// type classes, the fields and the data loaders; what is left to say here is the one record that exists only
/// for the schema, which is internal and therefore registered by name, and who answers a field's permission key.
/// </para>
/// </remarks>
internal static class TenantsGraphQL
{
    /// <summary>The name the schema is registered under, and the gateway knows it by.</summary>
    public const string SourceSchemaName = "tenants";

    /// <summary>
    /// Registers the schema when the host serves GraphQL, and answers its builder; <see langword="null"/> when
    /// the host serves none.
    /// </summary>
    /// <param name="services">The host's services.</param>
    /// <param name="host">The host's decisions, among them what every module's schema gets.</param>
    public static IRequestExecutorBuilder? AddTenantsGraphQL(this IServiceCollection services, ModuleHost host)
    {
        ArgumentNullException.ThrowIfNull(host);

        if (host.GraphQL is not { } conventions)
        {
            return null;
        }

        // Who answers the key a field of a role asks for. The host's conventions add the handler that asks.
        services.AddScoped<IFieldKeys<RoleListing>, RoleFieldKeys>();

        var schema = services
            .AddGraphQLServer(SourceSchemaName)
            // A schema a gateway composes: its lookups are how the gateway finds an entity by its key.
            .AddSourceSchemaDefaults()
            .AddDDDToolkitTypes()
            // Generated here: the module's ids as UUID scalars.
            .AddTenantsGraphQlRuntimeBindings()
            // Generated by HotChocolate, from the attribute in Module.cs: every [Query] and [Mutation] method of this
            // project as a field, the paged field of the one [QueryType] class with its connection, every
            // [ObjectType<T>] class as the type of its record, and the data loaders written from the [DataLoader]
            // methods.
            .AddTenantsTypes()
            // The one type with no record behind it: the tenant inside one of the caller's own seats.
            .AddObjectType<TenantOfSeat>();

        // What the host gives every module's schema: typed errors, one spelling for enum values, a scope per
        // field, the check that the caller has a seat, nullable fields for a type with a key, and a field's
        // permission key asked of the class above.
        conventions(schema);
        return schema;
    }
}
