using DDDToolkit.Abstractions.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGeneratorsToolkit.Providers;
using SourceGeneratorsToolkit.Providers.Contexts;
using SourceGeneratorsToolkit.SyntaxExtensions;
using System.Linq;
using System.Text;

namespace DDDToolkit.Analyzers.Generators;

[Generator]
public class EntityIdGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //#if DEBUG
        //        if (!System.Diagnostics.Debugger.IsAttached)
        //        {

        //            System.Diagnostics.Debugger.Launch();
        //        }
        //#endif

        var entities = context.FindAttributesProvider<EntityIdAttribute, RecordDeclarationSyntax>();
        context.RegisterSourceOutput(entities, Execute);
    }

    private static void Execute(SourceProductionContext context, TypeAttributeSyntaxContext data)
    {

        var recordDeclaration = data.TargetNode as RecordDeclarationSyntax;
        if (recordDeclaration is null)
        {
            return;
        }
        var name = recordDeclaration.GetName();
        var @namespace = recordDeclaration.GetNamespace();
        var accessModifier = recordDeclaration.GetAccessModifier();
        var type = data.Attributes.First(x => x.match).attribute.GenericTypes.First().Name;
        var arguments = data.Attributes.First(x => x.match).attribute.Arguments;
        var prefix = arguments.TryGetValue("Prefix", out var value) ? value!.Value!.ToString() : "";

        var sourceCode = $$$"""
                            // <auto-generated/>
                            using DDDToolkit.BaseTypes;
                            using DDDToolkit.Abstractions.Interfaces;
                            using System.Text.Json.Serialization;

                            #nullable enable
                            namespace {{{@namespace}}};
    
                            {{{accessModifier}}} partial record {{{name}}} : EntityId<{{{type}}}>
                            {
                                protected {{{name}}}({{{type}}} value) : base(value, "{{{prefix}}}")
                                {
                                }

                                [JsonConstructor]
                                protected {{{name}}}() : base("{{{prefix}}}", bypassValidation: true)
                                {
                                }

                                public override int GetHashCode()
                                    => base.GetHashCode();

                            {{{(type == "Guid" ?
                         $$$"""
                                public static {{{name}}} CreateUnique() => new(Guid.NewGuid());
                            """ : "")}}}  

                    
                            }
    
                            """;
        // Add the generated source to the compilation
        context.AddSource($"{@namespace}.{name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }

}
