using DDDToolkit.Supporting.Membership;
using Examples.Tenancy.Projects.Api.Crew.GraphQL;
using Examples.Tenancy.Projects.Api.GraphQl;
using Examples.Tenancy.Projects.Api.ProjectRoles.GraphQL;
using Examples.Tenancy.Projects.Application.Crew;
using Examples.Tenancy.Projects.Application.ProjectRoles;
using Examples.Hosting;
using DDDToolkit.HotChocolate;
using DDDToolkit.HotChocolate.Authorization;
using HotChocolate.Execution.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Examples.Tenancy.Projects.Api.GraphQL;

/// <summary>
/// Projects' GraphQL source schema: a schema of its own, which a gateway in the host composes with the other
/// modules' into the one schema a client sees.
/// </summary>
/// <remarks>
/// Projects owns the project, its crew and the tenant's project roles. A seat and a unit it names by id alone
/// (<see cref="ReferencedSeat"/>, <see cref="ReferencedOrganizationUnit"/>): what they are called is Tenancy's to
/// say, and the gateway asks Tenancy. A role a crew member holds is a project role, this schema's own. Each
/// feature's queries, mutations, types and loaders are in its own <c>GraphQL</c> folder, beside its routes; this
/// class only puts them together. A type of this schema is declared over the record the application's queries
/// answer with, in a class marked <c>[ObjectType&lt;T&gt;]</c>, which HotChocolate's generator registers. What has
/// no such record, a reference to another module's entity, is an internal record of this project and is
/// registered by name: HotChocolate infers an object type from a public class only.
/// </remarks>
internal static class ProjectsGraphQL
{
    /// <summary>The name the schema is registered under, and the gateway knows it by.</summary>
    public const string SourceSchemaName = "projects";

    /// <summary>
    /// Registers the schema when the host serves GraphQL, and answers its builder; <see langword="null"/> when
    /// the host serves none.
    /// </summary>
    /// <param name="services">The host's services.</param>
    /// <param name="host">The host's decisions, among them what every module's schema gets.</param>
    public static IRequestExecutorBuilder? AddProjectsGraphQL(this IServiceCollection services, ModuleHost host)
    {
        ArgumentNullException.ThrowIfNull(host);

        if (host.GraphQL is not { } conventions)
        {
            return null;
        }

        // Who answers a rule on a field of a crew member, and of a project role: asked by the key authorization the
        // host's conventions add.
        services.AddScoped<IFieldKeys<CrewOverview>, CrewFieldKeys>();
        services.AddScoped<IFieldKeys<ProjectRoleListing>, ProjectRoleFieldKeys>();

        var schema = services
            .AddGraphQLServer(SourceSchemaName)
            // A schema a gateway composes: its lookups are how the gateway finds an entity by its key.
            .AddSourceSchemaDefaults()
            // A project is a node: node(id:) finds one, through the same read the lookup uses.
            .AddGlobalObjectIdentification(options => options.MarkNodeFieldAsLookup = true)
            .AddDDDToolkitTypes()
            // Generated here: the module's ids, and the ids Tenancy publishes, as scalars and node ids.
            .AddProjectsGraphQlRuntimeBindings()
            // Generated by HotChocolate, from the attribute in Module.cs: every [Query] and [Mutation] method of this
            // project as a field, with the Query and Mutation types they are fields of; the types declared over the
            // application's answers; the paged list with its connection; and the data loaders.
            .AddProjectsTypes()
            .AddObjectType<ReferencedSeat>()
            .AddObjectType<ReferencedOrganizationUnit>()
            // The package's status of a role, under this schema's word for what it is the status of.
            .AddEnumType<KeptRoleStatus>(status => status.Name("ProjectRoleStatus"));

        // What the host gives every module's schema: typed errors, one spelling for enum values, a scope per
        // field, and the check that the caller has a seat.
        conventions(schema);
        return schema;
    }
}
