using System.Reflection;
using DDDToolkit.Exceptions;
using DDDToolkit.Interfaces;
using DDDToolkit.Tests.Domain;
using FluentAssertions;

namespace DDDToolkit.Tests.Invariants;

/// <summary>
/// The invariant seam without a database: what <c>EnsureInvariants()</c> does, what it throws, and
/// what an aggregate that states no invariants pays for the privilege (nothing).
/// </summary>
public class InvariantSeamTests
{
    private const byte Nop = 0x00;
    private const byte Ret = 0x2A;
    private const byte Call = 0x28;
    private const byte CallVirt = 0x6F;

    [Fact]
    public void EnsureInvariants_runs_the_seam_without_a_database()
    {
        var tab = new Tab(TabId.CreateUnique(), limit: 20m);
        tab.Order(new TabLineId(1), "Negroni", 12m);

        tab.Invoking(t => t.EnsureInvariants()).Should().NotThrow("the tab is within its limit");

        tab.Order(new TabLineId(2), "Negroni", 12m);

        tab.Invoking(t => t.EnsureInvariants()).Should().Throw<InvariantViolationException>();
    }

    [Fact]
    public void A_violation_names_the_aggregate_type_and_id_and_the_rule()
    {
        var id = TabId.CreateUnique();
        var tab = new Tab(id, limit: 5m);
        tab.Order(new TabLineId(1), "Champagne", 90m);

        var exception = tab.Invoking(t => t.EnsureInvariants()).Should().Throw<InvariantViolationException>().Which;

        exception.AggregateType.Should().Be<Tab>();
        exception.AggregateId.Should().Be(id);
        exception.Violations.Should().ContainSingle().Which.Should().Contain("may not exceed its limit");
        exception.Message.Should().Contain("Tab").And.Contain(id.ToString());
        exception.Should().BeAssignableTo<DDDToolkitException>("callers catch the toolkit's own base type");
        exception.Should().NotBeAssignableTo<ConcurrencyConflictException>("a broken rule is not a lost race");
    }

    [Fact]
    public void One_check_can_report_every_rule_it_broke()
    {
        var tab = new PickyTab(TabId.CreateUnique(), name: "   ", table: 0);

        var exception = tab.Invoking(t => t.EnsureInvariants()).Should().Throw<InvariantViolationException>().Which;

        exception.Violations.Should().HaveCount(2);
        exception.Message.Should().Contain("broke 2 invariants")
            .And.Contain("in someone's name")
            .And.Contain("at a real table");
    }

    [Fact]
    public void A_child_entity_has_a_seam_of_its_own_and_the_root_runs_it()
    {
        var line = new TabLine(new TabLineId(7), "Water", -1m);

        var exception = line.Invoking(l => l.EnsureInvariants()).Should().Throw<InvariantViolationException>().Which;
        exception.AggregateType.Should().Be<TabLine>();

        var tab = new Tab(TabId.CreateUnique(), limit: 100m);
        tab.Order(new TabLineId(7), "Water", 0m).Reprice(-1m);

        // Nothing in Tab mentions its lines. Asking the boundary asks what is inside it.
        tab.Invoking(t => t.EnsureInvariants()).Should().Throw<InvariantViolationException>()
            .Which.AggregateType.Should().Be<Tab>("the tab was the one asked, and it answers for the whole of itself");
    }

    [Fact]
    public void An_aggregate_with_no_invariants_behaves_exactly_as_before()
    {
        var tab = new QuietTab(TabId.CreateUnique());

        tab.Set(42);
        tab.Anything.Should().Be(42);

        tab.Invoking(t => t.EnsureInvariants()).Should().NotThrow();
        ((IHasInvariants)tab).EnsureInvariants();

        var basket = new Basket(BasketId.CreateUnique(), "someone");
        basket.Invoking(b => b.EnsureInvariants()).Should().NotThrow("aggregates written before the seam existed still work");
    }

    [Fact]
    public void Every_generated_entity_and_root_carries_the_seam()
    {
        foreach (var type in new[] { typeof(QuietTab), typeof(Tab), typeof(TabLine), typeof(Basket), typeof(BasketLine) })
        {
            type.Should().BeAssignableTo<IHasInvariants>($"{type.Name} is generated by the toolkit");
            Override(type).Should().NotBeNull($"{type.Name} overrides EnsureInvariants with its own seam");
        }

        // Only the types that actually stated a rule have a CheckInvariants method at all; the
        // others had theirs erased, which is the whole point of the shape.
        Seam(typeof(Tab)).Should().NotBeNull();
        Seam(typeof(TabLine)).Should().NotBeNull();
        Seam(typeof(QuietTab)).Should().BeNull();
        Seam(typeof(Basket)).Should().BeNull();
    }

    /// <summary>
    /// The reason the seam is a <c>partial void</c>. The compiler erases an unimplemented partial
    /// method and every call to it, so the override left on an aggregate that states no invariants
    /// does no work whatsoever. This reads the emitted IL rather than taking the claim on trust.
    /// </summary>
    [Fact]
    public void An_unimplemented_seam_costs_nothing_in_the_emitted_IL()
    {
        var quiet = Body(typeof(QuietTab));

        quiet.Should().OnlyContain(opcode => opcode == Nop || opcode == Ret, "an erased call leaves nothing but nop and ret");
        quiet.Should().NotContain(Call).And.NotContain(CallVirt);

        // The seam itself is erased outright: no method is emitted for it at all.
        typeof(QuietTab).GetMethod("CheckInvariants", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
            .Should().BeNull("an unimplemented partial method is not emitted");

        // And to prove the test can tell the difference, the same method on an aggregate that does
        // state an invariant calls into it.
        Body(typeof(Tab)).Should().Contain(Call);
        Seam(typeof(Tab)).Should().NotBeNull();
    }

    private static MethodInfo? Seam(Type type)
        => type.GetMethod("CheckInvariants", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly);

    private static MethodInfo? Override(Type type)
        => type.GetMethod(nameof(IHasInvariants.EnsureInvariants), BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly);

    private static byte[] Body(Type type)
        => Override(type)!.GetMethodBody()!.GetILAsByteArray()!;
}
