using DDDToolkit.Abstractions.Interfaces;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DDDToolkit.Serialization.Converters;

/// <summary>
/// Converts an id that implements <see cref="IEntityId{TValue}"/> without deriving from
/// <c>SingleValueObject&lt;TValue&gt;</c> - which is what every struct id does - to and from its underlying
/// value.
/// <para>
/// Ids generated by DDDToolkit carry their own nested <c>SystemTextJsonConverter</c> and
/// <see cref="SingleValueObjectConverterFactory"/> prefers that one; this converter covers hand written ids
/// and projects whose generator ran without System.Text.Json in scope. A struct id can never be null, so a
/// JSON <c>null</c> is an error for one - use <c>TheId?</c> to allow it.
/// </para>
/// </summary>
public sealed class EntityIdConverter<TEntityId, TValue> : JsonConverter<TEntityId>
    where TEntityId : IEntityId<TValue>
    where TValue : notnull
{
    private static readonly SingleValueDescription? Description = SingleValueDescription.For(typeof(TEntityId));

    private static bool AllowsNull => default(TEntityId) is null;

    /// <inheritdoc />
    public override TEntityId? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
        {
            return AllowsNull ? default : throw NullNotAllowed();
        }

        var value = JsonSerializer.Deserialize<TValue>(ref reader, options);
        if (value is null)
        {
            return AllowsNull ? default : throw NullNotAllowed();
        }

        return Create(value);
    }

    /// <inheritdoc />
    public override void Write(Utf8JsonWriter writer, TEntityId value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);

        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        JsonSerializer.Serialize(writer, value.Value, options);
    }

    /// <summary>Supports using the id as a dictionary key, through the converter of the wrapped value.</summary>
    public override TEntityId ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => Create(ValueConverter(options).ReadAsPropertyName(ref reader, typeof(TValue), options));

    /// <inheritdoc cref="ReadAsPropertyName" />
    public override void WriteAsPropertyName(Utf8JsonWriter writer, TEntityId value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        ValueConverter(options).WriteAsPropertyName(writer, value.Value, options);
    }

    private static TEntityId Create(TValue value)
    {
        if (Description?.CanCreate != true)
        {
            throw new JsonException($"Could not find a constructor for '{typeof(TEntityId).Name}' taking a single {typeof(TValue).Name}.");
        }

        return (TEntityId)Description.Create(value);
    }

    private static JsonException NullNotAllowed()
        => new($"Cannot convert null to '{typeof(TEntityId).Name}'. Declare the member as '{typeof(TEntityId).Name}?' to allow it.");

    private static JsonConverter<TValue> ValueConverter(JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        return (JsonConverter<TValue>)options.GetConverter(typeof(TValue));
    }
}
