using DDDToolkit.BaseTypes;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DDDToolkit.Serialization.Converters;

/// <summary>
/// Reads and writes every type that wraps a single value - single value objects, reference type ids
/// (<c>[EntityId&lt;T&gt;] partial record</c>) and struct ids
/// (<c>[EntityId&lt;T&gt;] readonly partial record struct</c>) - as the value it wraps, so
/// <c>{ "id": "3fa85f64-..." }</c> rather than <c>{ "id": { "value": "3fa85f64-..." } }</c>.
/// <para>
/// A struct id generated by DDDToolkit already carries
/// <c>[JsonConverter(typeof(TheId.SystemTextJsonConverter))]</c>. Converters registered on
/// <see cref="JsonSerializerOptions.Converters"/> take precedence over that attribute, so this factory
/// hands the generated converter back when there is one (keeping its prefixed dictionary keys) and falls
/// back to <see cref="EntityIdConverter{TEntityId, TValue}"/> otherwise.
/// </para>
/// <para>
/// <c>CatId?</c> and other nullable struct ids need no registration: System.Text.Json wraps the converter
/// for the underlying type. Always valid twins are matched by this factory as well, which is why
/// <see cref="BlockAlwaysValidSerialization"/> is registered before it.
/// </para>
/// </summary>
public class SingleValueObjectConverterFactory : JsonConverterFactory
{
    /// <summary>True for anything that wraps a single value; see <see cref="SingleValueDescription"/>.</summary>
    public override bool CanConvert(Type typeToConvert) => SingleValueDescription.For(typeToConvert) is not null;

    /// <summary>
    /// Builds the converter for <paramref name="typeToConvert"/>. Never throws for a type
    /// <see cref="CanConvert"/> accepted: a type that cannot be rebuilt from its value still gets a
    /// converter, which writes it correctly and reports the missing constructor when asked to read one.
    /// </summary>
    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);

        var description = SingleValueDescription.For(typeToConvert)
            ?? throw new NotSupportedException($"'{typeToConvert.Name}' does not wrap a single value; CanConvert would have declined it.");

        if (description.IsSingleValueObject)
        {
            return Instantiate(typeof(SingleValueObjectConverter<,>), typeToConvert, description.ValueType);
        }

        return GeneratedConverter(typeToConvert, options)
            ?? Instantiate(typeof(EntityIdConverter<,>), typeToConvert, description.ValueType);
    }

    private static JsonConverter Instantiate(Type converterDefinition, Type typeToConvert, Type valueType)
        => (JsonConverter)Activator.CreateInstance(converterDefinition.MakeGenericType(typeToConvert, valueType))!;

    /// <summary>The converter named by a <c>[JsonConverter]</c> attribute on the type itself, if it can be used.</summary>
    private static JsonConverter? GeneratedConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        var attribute = typeToConvert.GetCustomAttribute<JsonConverterAttribute>(inherit: false);
        if (attribute is null)
        {
            return null;
        }

        var converter = attribute.CreateConverter(typeToConvert);
        if (converter is null && attribute.ConverterType is { } converterType)
        {
            if (converterType == typeof(SingleValueObjectConverterFactory) || converterType.GetConstructor(Type.EmptyTypes) is null)
            {
                return null; // Would recurse into this factory, or cannot be constructed.
            }

            converter = Activator.CreateInstance(converterType) as JsonConverter;
        }

        if (converter is SingleValueObjectConverterFactory)
        {
            return null;
        }

        if (converter is JsonConverterFactory factory)
        {
            converter = factory.CanConvert(typeToConvert) ? factory.CreateConverter(typeToConvert, options) : null;
        }

        return converter?.CanConvert(typeToConvert) == true ? converter : null;
    }
}

/// <summary>
/// Converts a <see cref="SingleValueObject{TValue}"/> - which includes reference type ids, because
/// <see cref="EntityId{TIdType}"/> derives from it - to and from its underlying value. The instance is
/// rebuilt through the single argument constructor the generator emits, which is <c>protected</c>.
/// </summary>
public class SingleValueObjectConverter<TSingleValueObject, TValue> : JsonConverter<TSingleValueObject>
    where TSingleValueObject : SingleValueObject<TValue>
    where TValue : notnull
{
    private static readonly SingleValueDescription? Description = SingleValueDescription.For(typeof(TSingleValueObject));

    /// <inheritdoc />
    public override TSingleValueObject? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        var value = JsonSerializer.Deserialize<TValue>(ref reader, options);
        return value is null ? null : Create(value);
    }

    /// <inheritdoc />
    public override void Write(Utf8JsonWriter writer, TSingleValueObject value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);

        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        JsonSerializer.Serialize(writer, value.Value, options);
    }

    /// <summary>Supports using the type as a dictionary key, through the converter of the wrapped value.</summary>
    public override TSingleValueObject ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => Create(ValueConverter(options).ReadAsPropertyName(ref reader, typeof(TValue), options));

    /// <inheritdoc cref="ReadAsPropertyName" />
    public override void WriteAsPropertyName(Utf8JsonWriter writer, TSingleValueObject value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        ValueConverter(options).WriteAsPropertyName(writer, value.Value, options);
    }

    private static TSingleValueObject Create(TValue value)
    {
        if (Description?.CanCreate != true)
        {
            throw new JsonException($"Could not find a constructor for '{typeof(TSingleValueObject).Name}' taking a single {typeof(TValue).Name}.");
        }

        return (TSingleValueObject)Description.Create(value);
    }

    private static JsonConverter<TValue> ValueConverter(JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        return (JsonConverter<TValue>)options.GetConverter(typeof(TValue));
    }
}
