using System.Reflection;
using DDDToolkit.Abstractions.Attributes;
using DDDToolkit.BaseTypes;
using DDDToolkit.Analyzers.Tests.Generation;
using Microsoft.CodeAnalysis;

namespace DDDToolkit.Analyzers.Tests.Integrations;

/// <summary>
/// <c>DDD_DeclareModule</c>: with it set to true beside <c>DDD_Module</c>, the build declares the project's module, so a
/// <c>Directory.Build.props</c> replaces a <c>Module.cs</c> in every project of a module. The targets of the
/// DDDToolkit.Analyzers package write the two properties into the project as <c>AssemblyMetadata</c>, which every
/// generator of it reads, and the toolkit's generator writes <c>[assembly: Module]</c> from them, for the analyzers, the
/// runtime and every project that references the assembly.
/// <para>
/// Each test compiles the file those targets write, read from the targets themselves (<see cref="ModuleDeclarationFile"/>).
/// The first half is about the attribute: written where the project declares none, never beside one it declares, in a
/// file of its own or through an <c>AssemblyAttribute</c> item, so never twice; and not at all for <c>DDD_Module</c>
/// alone, which still only names the generated code. The second half is everything that follows from the module: the
/// names, the registrations of a module in layers, the boundary, and where the diagnostics about it point. The last is
/// DDD00064, for projects named after one module that are not taken together, because one of them declares no module,
/// or neither does and a registration is written for nobody.
/// </para>
/// </summary>
public class ModuleFromTheBuildTests
{
    /// <summary>A domain project of module Ordering: an id and a domain event, and no module of its own.</summary>
    private const string OrderingDomain =
        """
        using System;
        using DDDToolkit.Abstractions.Attributes;
        using DDDToolkit.BaseTypes;

        namespace Acme.Ordering.Domain;

        [EntityId<Guid>]
        public readonly partial record struct OrderId;

        public sealed record OrderPlaced(OrderId Order) : DomainEvent;
        """;

    private const string Declared = "[assembly: global::DDDToolkit.Abstractions.Attributes.ModuleAttribute(\"Ordering\")]";

    private static GeneratorTestHost Domain(string source = OrderingDomain)
        => GeneratorTestHost.Create(source, "Domain.cs").WithAssemblyName("Acme.Ordering.Domain");

    /// <summary>The <c>[assembly: Module]</c> attributes the compiled assembly carries, as the runtime and reflection read them.</summary>
    private static List<string> ModulesOf(GeneratorRunOutcome result)
        => [.. result.Emit().Assembly.GetCustomAttributes<ModuleAttribute>().Select(attribute => attribute.Name)];

    // ------------------------------------------------------------------ the attribute

    [Fact]
    public void The_build_declares_the_module_and_the_assembly_carries_it()
    {
        var result = Domain().WithModuleFromTheBuild("Ordering").RunCore();

        result.ShouldCompile();
        result.ReportedDiagnostics.Should().BeEmpty();
        result.ShouldContain("Module.g.cs", Declared);
        ModulesOf(result).Should().Equal(["Ordering"], "a project that references the assembly, and the runtime, read the module from it");
    }

    [Fact]
    public void A_module_declared_in_the_projects_source_wins_and_nothing_is_written_beside_it()
    {
        // DDD_Module comes from a Directory.Build.props that covers the folder; the project says otherwise itself.
        var result = Domain()
            .WithSource("[assembly: DDDToolkit.Abstractions.Attributes.Module(\"Sales\")]", "Module.cs")
            .WithModuleFromTheBuild("Ordering")
            .RunCore();

        result.ShouldCompile();
        result.HintNames.Should().NotContain("Module.g.cs");
        result.ShouldContain("EventNames", "public static class SalesEventNames", "the attribute names the generated code, as it always does");
        result.ShouldContain("EventNames", "\"sales.order-placed\"");
        ModulesOf(result).Should().Equal(["Sales"]);
    }

    [Fact]
    public void A_module_an_AssemblyAttribute_item_declares_is_kept_and_nothing_is_written_beside_it()
    {
        // What the SDK writes into obj/ for <AssemblyAttribute Include="DDDToolkit.Abstractions.Attributes.ModuleAttribute">
        // with _Parameter1 = $(DDD_Module): a project that declared its module this way before the build could.
        const string AssemblyInfo =
            """
            // <auto-generated/>
            using System;
            using System.Reflection;

            [assembly: DDDToolkit.Abstractions.Attributes.ModuleAttribute("Ordering")]
            [assembly: System.Reflection.AssemblyCompanyAttribute("Acme.Ordering.Domain")]
            """;

        var result = Domain()
            .WithSource(AssemblyInfo, "obj/Debug/net10.0/Acme.Ordering.Domain.AssemblyInfo.cs")
            .WithModuleFromTheBuild("Ordering")
            .RunCore();

        result.ShouldCompile();
        result.HintNames.Should().NotContain("Module.g.cs");
        ModulesOf(result).Should().Equal(["Ordering"]);
    }

    [Theory]
    [InlineData("a file of the project")]
    [InlineData("an AssemblyAttribute item")]
    [InlineData("the build")]
    [InlineData("an attribute that names no module")]
    public void The_module_is_never_declared_twice(string declaredBy)
    {
        var host = Domain().WithModuleFromTheBuild("Ordering");
        host = declaredBy switch
        {
            "a file of the project" => host.WithSource("[assembly: DDDToolkit.Abstractions.Attributes.Module(\"Ordering\")]", "Module.cs"),
            "an AssemblyAttribute item" => host.WithSource("[assembly: DDDToolkit.Abstractions.Attributes.ModuleAttribute(\"Ordering\")]", "obj/Debug/net10.0/Acme.Ordering.Domain.AssemblyInfo.cs"),
            "an attribute that names no module" => host.WithSource("[assembly: DDDToolkit.Abstractions.Attributes.Module(\" \")]", "Module.cs"),
            _ => host,
        };

        var result = host.RunCore();

        result.CompilationDiagnostics.Should().NotContain(diagnostic => diagnostic.Id == "CS0579", "a second [assembly: Module] does not compile");
        result.OutputCompilation.Assembly.GetAttributes()
            .Count(attribute => attribute.AttributeClass?.ToDisplayString() == "DDDToolkit.Abstractions.Attributes.ModuleAttribute")
            .Should().Be(1, "{0} declares it, and nothing else does", declaredBy);
    }

    [Fact]
    public void An_attribute_that_names_no_module_is_not_made_up_for_by_the_build()
    {
        // The attribute is there, so nothing writes a second one; were the build's name read anyway, the generators
        // and the runtime would name the module differently.
        var result = Domain()
            .WithSource("[assembly: DDDToolkit.Abstractions.Attributes.Module(\" \")]", "Module.cs")
            .WithModuleFromTheBuild("Ordering")
            .RunCore();

        result.HintNames.Should().NotContain("Module.g.cs");
        result.ShouldContain("EventNames", "\"order-placed\"", "no module, so the event is named after its class alone");
    }

    [Fact]
    public void A_project_with_neither_the_attribute_nor_the_build_s_word_declares_nothing()
    {
        var result = Domain().RunCore();

        result.ShouldCompile();
        result.HintNames.Should().NotContain("Module.g.cs");
        ModulesOf(result).Should().BeEmpty();
    }

    [Theory]
    [InlineData(null)]
    [InlineData("false")]
    public void DDD_Module_alone_still_only_names_the_generated_code(string? declares)
    {
        // What every project that set DDD_Module before DDD_DeclareModule existed has: the name, and no module. A
        // project that says it is no module, and a test project, have the same, with the build's false beside it.
        var result = Domain().WithModuleFromTheBuild("Ordering", declares).RunCore();

        result.ShouldCompile();
        result.HintNames.Should().NotContain("Module.g.cs");
        result.ShouldContain("EventNames", "public static class OrderingEventNames", "DDD_Module names the class, as before");
        result.ShouldContain("EventNames", "public const string OrderPlaced = \"order-placed\";", "and the event keeps the name it was stored under");

        var emitted = result.Emit();
        emitted.Assembly.GetCustomAttributes<ModuleAttribute>().Should().BeEmpty();
        DomainEventName.Of(emitted.Type("Acme.Ordering.Domain.OrderPlaced")).Should().Be("order-placed");
    }

    [Fact]
    public void A_module_name_that_is_not_an_identifier_is_written_as_it_is_and_spelled_as_one_in_names()
    {
        var result = Domain().WithModuleFromTheBuild("order-management").RunCore();

        result.ShouldCompile();
        result.ShouldContain("Module.g.cs", "ModuleAttribute(\"order-management\")]");
        result.ShouldContain("EventNames", "public static class OrderManagementEventNames");
        result.ShouldContain("EventNames", "\"order-management.order-placed\"");
    }

    // ------------------------------------------------------------------ every generator of the project sees it

    [Fact]
    public void The_projects_events_are_named_after_the_module_as_the_runtime_names_them()
    {
        // The generator that names the events cannot see the attribute written beside it; it reads the build's word,
        // and the runtime reads the attribute. The two have to come to the same name, or a stored event is lost.
        var result = Domain().WithModuleFromTheBuild("Ordering").RunCore();

        result.ShouldContain("EventNames", "public static class OrderingEventNames");
        result.ShouldContain("EventNames", "public const string OrderPlaced = \"ordering.order-placed\";");

        var emitted = result.Emit();
        var constant = (string)emitted.Type("Acme.Ordering.Domain.OrderingEventNames").GetField("OrderPlaced")!.GetRawConstantValue()!;
        constant.Should().Be(DomainEventName.Of(emitted.Type("Acme.Ordering.Domain.OrderPlaced")));
    }

    [Fact]
    public void The_registrations_are_named_after_the_module_and_spelled_as_one()
    {
        var result = Domain()
            .WithEntityFramework()
            .WithModuleFromTheBuild("order-management")
            .RunCoreAnd(GeneratorTestHost.EntityFrameworkGenerators());

        result.ShouldCompile();
        result.ShouldContain("ConverterExtensions", " AddOrderManagementConverters(", "the module's name, where DDD_Module alone is taken as it is written");
    }

    [Fact]
    public void An_access_function_named_without_its_schema_belongs_to_the_module_the_build_declared()
    {
        var result = GeneratorTestHost.Create(
                """
                using System;
                using DDDToolkit.Abstractions.Access;
                using DDDToolkit.Abstractions.Attributes;

                namespace Acme.Ordering.Domain;

                [EntityId<Guid>]
                public readonly partial record struct OrderId;

                [AggregateRoot<OrderId>]
                public partial class Order
                {
                    public Order(OrderId id) : base(id) { }

                    public bool IsPublic { get; private set; }
                }

                [AccessFunction<Order>("is_public")]
                public static partial class PublicOrders
                {
                    public static bool Allows(Order order, Caller caller) => order.IsPublic;
                }
                """)
            .WithModuleFromTheBuild("Ordering")
            .RunCore();

        result.ShouldNotHaveDiagnostic("DDD00052");
        result.ShouldCompile();
        result.ShouldContain("PublicOrders.AccessFunction", "public const string Name = \"ordering/is_public\";");
    }

    /// <summary>
    /// A module's infrastructure project, which declares none of the classes and calls the registration without type
    /// arguments: it compiles only against the wrapper written from the domain project's classes.
    /// </summary>
    private const string Infrastructure =
        """
        using System.Collections.Generic;
        using Sample.Tenancy;

        namespace Shop.Infrastructure;

        public static class Startup
        {
            public static List<string> Register() => new Registry().AddTenancy().Entries;
        }
        """;

    /// <summary>The shop's domain project: its tenant, organization and units, declared with the package's templates.</summary>
    private static GeneratorTestHost ShopDomain(GeneratorTestHost project, string? declares = "true")
        => project
            .WithModuleFromTheBuild("Shop", declares)
            .WithSource(TemplateEntityTests.Ids.Replace("namespace Sample;", "namespace Shop.Domain;", StringComparison.Ordinal), "Ids.cs")
            .WithSource(TemplateEntityTests.Application.Replace("namespace Sample;", "namespace Shop.Domain;", StringComparison.Ordinal), "Classes.cs");

    private static GeneratorTestHost ShopInfrastructure(string source = Infrastructure, string? domainDeclares = "true")
        => GeneratorTestHost.Create(source, "Startup.cs")
            .WithAssemblyName("Shop.Infrastructure")
            .WithReferencedAssembly(TemplateEntityTests.Package, "Sample.Tenancy")
            .WithReferencedProject("Shop.Domain", project => ShopDomain(project, domainDeclares))
            .WithReferencedAssembly(TemplateRegistrationTests.Registrations, "Sample.Tenancy.Registrations");

    [Fact]
    public void A_project_the_build_declared_gets_the_registrations_closed_over_the_classes_of_its_modules_other_projects()
    {
        // The case that had every project of a module in layers carry a Module.cs: without one here, AddTenancy() was
        // never written, and the call above it was CS1061.
        var result = ShopInfrastructure().WithModuleFromTheBuild("Shop").RunCore();

        result.ShouldCompile();
        result.ReportedDiagnostics.Should().BeEmpty();
        result.ShouldContain(
            "TenancyRegistrations.AddTenancy.Registration.",
            "=> global::Sample.Tenancy.TenancyRegistrations.AddTenancy<global::Shop.Domain.ShopTenant, global::Shop.Domain.TenantId, global::Shop.Domain.ShopOrganization, global::Shop.Domain.OrganizationId, global::Shop.Domain.ShopUnit, global::Shop.Domain.UnitId>(registry);");
    }

    [Theory]
    [InlineData("the build")]
    [InlineData("an AssemblyAttribute item")]
    public void A_template_the_module_declares_nowhere_is_DDD00049_at_the_project_file(string declaredBy)
    {
        // The project has no [assembly: Module] for the diagnostic to point at, or has one in the AssemblyInfo.cs
        // the SDK writes into obj/; either way the file somebody edits to declare the module is the project file.
        var host = GeneratorTestHost.Create("namespace Shop.Infrastructure;\n\npublic static class Nothing;", "Nothing.cs")
            .WithAssemblyName("Shop.Infrastructure")
            .WithReferencedAssembly(TemplateEntityTests.Package, "Sample.Tenancy")
            .WithReferencedProject("Shop.Domain", project => project
                .WithModuleFromTheBuild("Shop")
                .WithSource(TemplateEntityTests.Ids.Replace("namespace Sample;", "namespace Shop.Domain;", StringComparison.Ordinal), "Ids.cs")
                .WithSource(
                    """
                    namespace Shop.Domain;

                    [Sample.Tenancy.TenantAggregate<TenantId>]
                    public sealed partial class OnlyTenant
                    {
                        public OnlyTenant(TenantId id, string name) : base(id, name) { }
                    }
                    """,
                    "Classes.cs"))
            .WithReferencedAssembly(TemplateRegistrationTests.Registrations, "Sample.Tenancy.Registrations");
        host = declaredBy == "the build"
            ? host.WithModuleFromTheBuild("Shop")
            : host.WithModule("Shop").WithSource(
                """
                //------------------------------------------------------------------------------
                // <auto-generated>
                //     This code was generated by a tool.
                // </auto-generated>
                //------------------------------------------------------------------------------

                [assembly: DDDToolkit.Abstractions.Attributes.ModuleAttribute("Shop")]
                """,
                "obj/Debug/net10.0/Shop.Infrastructure.AssemblyInfo.cs");

        var result = host.RunCore();

        var reported = result.ReportedDiagnostics.Where(diagnostic => diagnostic.Id == "DDD00049").ToList();
        reported.Should().HaveCount(2, "the organization and the unit are both missing");
        reported.Should().OnlyContain(diagnostic => diagnostic.Location.GetLineSpan().Path == host.ProjectFile, "the project file is where the module is declared");
        result.CompilationErrors.Should().BeEmpty();
    }

    [Fact]
    public void Its_integration_event_registration_names_the_domain_events_of_the_modules_other_projects()
    {
        var result = GeneratorTestHost.Create("namespace Acme.Ordering.Infrastructure;\n\npublic static class Nothing;", "Nothing.cs")
            .WithAssemblyName("Acme.Ordering.Infrastructure")
            .WithEntityFrameworkRuntime()
            .WithReferencedProject("Acme.Ordering.Domain", project => project.WithSource(OrderingDomain, "Domain.cs").WithModuleFromTheBuild("Ordering"))
            .WithModuleFromTheBuild("Ordering")
            .RunCoreAnd(GeneratorTestHost.EntityFrameworkGenerators());

        result.ShouldCompile();
        result.ReportedDiagnostics.Should().BeEmpty();
        result.ShouldContain("IntegrationEventExtensions", " AddOrderingIntegrationEvents(");
        result.ShouldContain("IntegrationEventExtensions", "outbox.RegisterEvent<global::Acme.Ordering.Domain.OrderPlaced>(\"ordering.order-placed\", 1);");
        result.ShouldContain("ConverterExtensions", "OrderId", "the domain project's id is the module's, so this project converts it");
    }

    // ------------------------------------------------------------------ the boundary

    private const string CrmDomain =
        """
        using System;
        using DDDToolkit.Abstractions.Attributes;

        namespace Crm;

        [ModuleContract]
        [EntityId<Guid>]
        public readonly partial record struct CustomerId;

        [AggregateRoot<CustomerId>]
        public partial class Customer
        {
            public string Name { get; private set; } = string.Empty;
        }
        """;

    private const string SalesReport =
        """
        using Crm;

        namespace Sales;

        public sealed class OrderReport
        {
            public string Describe(Customer customer) => customer.Name;
        }
        """;

    [Fact]
    public void Another_module_that_names_what_a_module_the_build_declared_does_not_publish_is_DDD00022()
    {
        var result = GeneratorTestHost.Create(SalesReport)
            .WithModuleFromTheBuild("Sales")
            .WithReferencedProject("Crm.Domain", project => project.WithSource(CrmDomain, "Crm.cs").WithModuleFromTheBuild("Crm"))
            .WithAnalyzers(GeneratorTestHost.CoreAnalyzers())
            .RunCore();

        result.ShouldCompile();
        result.ShouldHaveDiagnostic("DDD00022", at: "Customer").GetMessage().Should().Contain("module 'Crm'").And.Contain("module 'Sales'");
    }

    [Fact]
    public void A_project_of_the_same_module_the_build_declared_names_it_freely()
    {
        var result = GeneratorTestHost.Create(SalesReport.Replace("namespace Sales;", "namespace Crm.Reports;", StringComparison.Ordinal))
            .WithModuleFromTheBuild("Crm")
            .WithReferencedProject("Crm.Domain", project => project.WithSource(CrmDomain, "Crm.cs").WithModuleFromTheBuild("Crm"))
            .WithAnalyzers(GeneratorTestHost.CoreAnalyzers())
            .RunCore();

        result.ShouldCompile();
        result.ShouldNotHaveDiagnostic("DDD00022");
    }

    // ------------------------------------------------------------------ DDD00064

    [Fact]
    public void A_project_named_after_a_module_it_references_that_declares_none_is_DDD00064_at_its_project_file()
    {
        // The infrastructure project carries the module's name and was left without DDD_DeclareModule: it is no project
        // of the module, so AddTenancy() is not written and its call does not compile, which is all one used to hear.
        var host = ShopInfrastructure("namespace Shop.Infrastructure;\n\npublic static class Nothing;").WithModuleFromTheBuild("Shop", declares: null);

        var result = host.RunCore();

        var diagnostic = result.ReportedDiagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "DDD00064").Subject;
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Warning);
        diagnostic.Location.GetLineSpan().Path.Should().Be(host.ProjectFile);
        diagnostic.GetMessage().Should().Be(
            "This project and project 'Shop.Domain', which it references, set DDD_Module to 'Shop', and only that project declares the module, "
            + "so the generators do not take this project for one of the module's projects, and nothing is written here from what the others declare. "
            + "Declare module 'Shop' in this project: <DDD_DeclareModule>true</DDD_DeclareModule> beside DDD_Module, or [assembly: Module(\"Shop\")].");
        result.HintNames.Should().NotContain("Registration");
    }

    [Fact]
    public void A_project_of_a_module_that_references_one_named_after_it_that_declares_none_is_DDD00064_naming_that_one()
    {
        var host = ShopInfrastructure("namespace Shop.Infrastructure;\n\npublic static class Nothing;", domainDeclares: null).WithModuleFromTheBuild("Shop");

        var result = host.RunCore();

        var diagnostic = result.ReportedDiagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "DDD00064").Subject;
        diagnostic.Location.GetLineSpan().Path.Should().Be(host.ProjectFile);
        diagnostic.GetMessage().Should().Be(
            "This project and project 'Shop.Domain', which it references, set DDD_Module to 'Shop', and only this project declares the module, "
            + "so the generators do not take that project for one of the module's projects, and its ids, domain events and template classes are left out of what is written here. "
            + "Declare module 'Shop' in that project: <DDD_DeclareModule>true</DDD_DeclareModule> beside DDD_Module, or [assembly: Module(\"Shop\")].");
        result.HintNames.Should().NotContain("Registration", "the classes are the domain project's, and it is no project of the module");
    }

    [Fact]
    public void Two_projects_named_after_one_module_that_neither_declares_are_DDD00064_where_a_registration_is_written_for_nobody()
    {
        // The trap of removing an AssemblyAttribute item that declared the module, without setting DDD_DeclareModule in
        // its place: both projects keep the name and neither is the module's, so AddTenancy() is written nowhere.
        var host = ShopInfrastructure(domainDeclares: null).WithModuleFromTheBuild("Shop", declares: null);

        var result = host.RunCore();

        var diagnostic = result.ReportedDiagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "DDD00064").Subject;
        diagnostic.Location.GetLineSpan().Path.Should().Be(host.ProjectFile);
        diagnostic.GetMessage().Should().Be(
            "This project and project 'Shop.Domain', which it references, set DDD_Module to 'Shop', and neither declares the module, "
            + "so the generators take neither for one of the module's projects, and nothing is written here for the classes that project declares with a template: AddTenancy, AddTenancyDefaults, AddTenancyWith. "
            + "Declare module 'Shop' in both: <DDD_DeclareModule>true</DDD_DeclareModule> beside DDD_Module, or [assembly: Module(\"Shop\")].");
        result.CompilationErrors.Should().ContainSingle(error => error.Id == "CS0411", "AddTenancy() without type arguments is written nowhere, so the call reaches the package's open method: the error the warning explains");
    }

    [Fact]
    public void Two_projects_named_after_one_module_without_templates_are_how_an_application_without_modules_names_its_code_and_not_DDD00064()
    {
        // What a 3.1 application has that sets DDD_Module for every project in its Directory.Build.props: ids and events
        // in one project, the context in the next, and no module. Nothing is written for nobody, so nothing is said.
        var result = GeneratorTestHost.Create("namespace Acme.Ordering.Infrastructure;\n\npublic static class Nothing;", "Nothing.cs")
            .WithAssemblyName("Acme.Ordering.Infrastructure")
            .WithReferencedProject("Acme.Ordering.Domain", project => project.WithSource(OrderingDomain, "Domain.cs").WithModuleFromTheBuild("Ordering", declares: null))
            .WithModuleFromTheBuild("Ordering", declares: null)
            .RunCore();

        result.ShouldCompile();
        result.ShouldNotHaveDiagnostic("DDD00064");
    }

    [Fact]
    public void Template_classes_whose_own_project_registers_them_are_written_for_and_not_DDD00064()
    {
        // The domain project sees the registrations itself, so it is written its own AddTenancy(); a project above it
        // that shares its name and is no module calls that one.
        var result = GeneratorTestHost.Create("namespace Shop.Infrastructure;\n\npublic static class Nothing;", "Nothing.cs")
            .WithAssemblyName("Shop.Infrastructure")
            .WithReferencedAssembly(TemplateEntityTests.Package, "Sample.Tenancy")
            .WithReferencedAssembly(TemplateRegistrationTests.Registrations, "Sample.Tenancy.Registrations")
            .WithReferencedProject("Shop.Domain", project => ShopDomain(project, declares: null))
            .WithModuleFromTheBuild("Shop", declares: null)
            .RunCore();

        result.ShouldCompile();
        result.ShouldNotHaveDiagnostic("DDD00064");
    }

    [Fact]
    public void A_project_that_declares_template_classes_of_the_registration_itself_takes_the_rest_and_is_not_DDD00064()
    {
        // This project declares the tenant and is written the registration for it, taking the organization and the
        // units from the project it references, module or not: nothing is left without one.
        var result = GeneratorTestHost.Create(
                """
                namespace Shop.Infrastructure;

                [Sample.Tenancy.TenantAggregate<Shop.Domain.TenantId>]
                public sealed partial class ShopTenantHere
                {
                    public ShopTenantHere(Shop.Domain.TenantId id, string name) : base(id, name) { }
                }
                """,
                "Tenant.cs")
            .WithAssemblyName("Shop.Infrastructure")
            .WithReferencedAssembly(TemplateEntityTests.Package, "Sample.Tenancy")
            .WithReferencedProject("Shop.Domain", project => ShopDomain(project, declares: null))
            .WithReferencedAssembly(TemplateRegistrationTests.Registrations, "Sample.Tenancy.Registrations")
            .WithModuleFromTheBuild("Shop", declares: null)
            .RunCore();

        result.ShouldNotHaveDiagnostic("DDD00064");
        result.HintNames.Should().Contain("AddTenancy.Registration", "the registration is written here, for this project's tenant and the domain project's other classes");
    }

    [Fact]
    public void A_project_that_says_it_is_no_module_is_not_DDD00064_either_way()
    {
        // DDD_DeclareModule false, or a test project, which the build writes the same for.
        ShopInfrastructure("namespace Shop.Infrastructure;\n\npublic static class Nothing;").WithModuleFromTheBuild("Shop", declares: "false")
            .RunCore().ShouldNotHaveDiagnostic("DDD00064");

        ShopInfrastructure("namespace Shop.Infrastructure;\n\npublic static class Nothing;", domainDeclares: "false").WithModuleFromTheBuild("Shop")
            .RunCore().ShouldNotHaveDiagnostic("DDD00064");
    }

    [Fact]
    public void Projects_named_after_another_module_are_not_DDD00064()
    {
        ShopInfrastructure("namespace Shop.Infrastructure;\n\npublic static class Nothing;").WithModuleFromTheBuild("Billing", declares: null)
            .RunCore().ShouldNotHaveDiagnostic("DDD00064");

        ShopInfrastructure("namespace Shop.Infrastructure;\n\npublic static class Nothing;", domainDeclares: null).WithModuleFromTheBuild("Billing")
            .RunCore().ShouldNotHaveDiagnostic("DDD00064");
    }

    [Fact]
    public void A_project_named_after_a_module_with_a_Module_cs_is_one_of_its_projects_and_not_DDD00064()
        => ShopInfrastructure()
            .WithModule("Shop")
            .WithSource("[assembly: DDDToolkit.Abstractions.Attributes.Module(\"Shop\")]", "Module.cs")
            .RunCore()
            .ShouldCompile()
            .ShouldNotHaveDiagnostic("DDD00064");

    [Fact]
    public void A_reference_built_without_the_build_s_word_cannot_be_told_and_is_not_DDD00064()
    {
        // An assembly an earlier version built, or one built without the targets: it carries no DDD_Module to compare.
        var result = GeneratorTestHost.Create("namespace Shop.Infrastructure;\n\npublic static class Nothing;", "Nothing.cs")
            .WithAssemblyName("Shop.Infrastructure")
            .WithReferencedProject("Shop.Domain", project => project.WithModule("Shop").WithSource(OrderingDomain, "Domain.cs"))
            .WithModuleFromTheBuild("Shop")
            .RunCore();

        result.ShouldCompile();
        result.ShouldNotHaveDiagnostic("DDD00064");
    }

    // ------------------------------------------------------------------ incremental

    [Fact]
    public void The_attribute_and_the_diagnostics_are_cached_across_an_unrelated_edit()
    {
        var first = Domain().WithModuleFromTheBuild("Ordering").RunCore();

        var second = first.RunAgain((compilation, options) => compilation.AddSyntaxTrees(
            Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText("namespace Acme.Ordering.Domain;\n\ninternal static class Unrelated;", options, "Unrelated.cs")));

        second.ShouldContain("Module.g.cs", Declared);
        second.Driver.GetRunResult().Results
            .Single(result => result.Generator.GetGeneratorType() == typeof(ModuleGenerator))
            .TrackedOutputSteps.SelectMany(step => step.Value).SelectMany(run => run.Outputs).Select(output => output.Reason)
            .Should().OnlyContain(reason => reason == IncrementalStepRunReason.Cached || reason == IncrementalStepRunReason.Unchanged);
    }
}
