using System.Diagnostics;
using System.Text.Json;

namespace DDDToolkit.Analyzers.Tests.Integrations;

/// <summary>
/// The build step of the DDDToolkit.Analyzers package as MSBuild runs it: which projects <c>DDD_Module</c> declares a
/// module in, and what the step hands the compiler there. A small project imports the targets file, sets what a project
/// file sets, and runs the step; the file it wrote and the <c>Compile</c> item it added are what the compiler gets.
/// <see cref="ModuleFromTheBuildTests"/> compiles that file; these say which projects are given it: every project that
/// sets <c>DDD_Module</c>, but a test project and one that sets <c>DDD_DeclareModule</c> to false. And that the
/// targets tell the generators they were imported, which DDD00064 asks.
/// </summary>
public sealed class ModuleTargetsTests : IDisposable
{
    private readonly string _project = Path.Combine(Path.GetTempPath(), "ddd-module-targets-" + Guid.NewGuid().ToString("N"));

    public ModuleTargetsTests() => Directory.CreateDirectory(_project);

    public void Dispose() => Directory.Delete(_project, recursive: true);

    [Fact]
    public async Task A_project_that_sets_DDD_Module_is_declared_that_module()
    {
        var declaration = await DeclarationAsync(new() { ["DDD_Module"] = " Ordering " });

        declaration.Should().Contain("[assembly: global::System.Reflection.AssemblyMetadata(\"DDD_Module\", \"Ordering\")]", "the name is trimmed, as the generators trim it");
        declaration.Should().StartWith("// <auto-generated/>", "the analyzers take it for generated code");
    }

    [Theory]
    [InlineData("DDD_DeclareModule", "false")]
    [InlineData("DDD_DeclareModule", " False ")]
    [InlineData("IsTestProject", "true")]
    [InlineData("IsTestingPlatformApplication", "true")]
    public async Task A_project_that_sets_DDD_Module_is_declared_no_module_where_it_says_so_or_is_a_test_project(string property, string value)
        => (await DeclarationAsync(new() { ["DDD_Module"] = "Ordering", [property] = value })).Should().BeNull();

    [Theory]
    [InlineData("true")]
    [InlineData("")]
    public async Task DDD_DeclareModule_set_to_anything_but_false_leaves_the_module_declared(string value)
        => (await DeclarationAsync(new() { ["DDD_Module"] = "Ordering", ["DDD_DeclareModule"] = value }))
            .Should().Contain("AssemblyMetadata(\"DDD_Module\", \"Ordering\")");

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public async Task A_project_without_a_DDD_Module_is_declared_nothing(string value)
        => (await DeclarationAsync(new() { ["DDD_Module"] = value })).Should().BeNull();

    [Fact]
    public async Task A_name_with_what_MSBuild_and_CSharp_read_in_it_reaches_the_compiler_as_it_is_written()
    {
        // ; splits an item, % and $ are MSBuild's own, and " and \ end or escape a C# string.
        var declaration = await DeclarationAsync(new() { ["DDD_Module"] = "order;\"management\" \\ 50% $x" });

        declaration.Should().Contain("AssemblyMetadata(\"DDD_Module\", \"order;\\\"management\\\" \\\\ 50% $x\")]");
    }

    [Theory]
    [InlineData("Ordering")]
    [InlineData("")]
    public async Task The_targets_hand_the_generators_DDD_DeclareModule_in_every_project_so_they_can_tell_the_step_ran(string module)
    {
        // Declared or not, a test project included: where it arrives, the generators leave the module to the step.
        var visible = (await ItemsAsync(new() { ["DDD_Module"] = module, ["IsTestProject"] = "true" }, "CompilerVisibleProperty"))
            .Select(item => item.GetProperty("Identity").GetString())
            .ToList();

        visible.Should().Contain("DDD_DeclareModule", "a generator that gets DDD_Module and not this reports DDD00064");
    }

    /// <summary>
    /// Runs the step in a project that sets <paramref name="properties"/>, and hands back the file it added to the
    /// project's <c>Compile</c> items, or null when it added none.
    /// </summary>
    private async Task<string?> DeclarationAsync(Dictionary<string, string> properties)
    {
        var compiled = (await ItemsAsync(properties, "Compile"))
            .Select(item => item.GetProperty("FullPath").GetString()!)
            .ToList();

        compiled.Should().HaveCountLessThan(2, "the step declares the module in one file");
        return compiled.Count == 0 ? null : File.ReadAllText(compiled[0]).ReplaceLineEndings("\n");
    }

    /// <summary>
    /// Runs the step in a project that sets <paramref name="properties"/>, and hands back the project's items of type
    /// <paramref name="itemType"/> as MSBuild prints them afterwards.
    /// </summary>
    private async Task<List<JsonElement>> ItemsAsync(Dictionary<string, string> properties, string itemType)
    {
        var targets = Path.Combine(RepositoryRoot(), "Source", "DDDToolkit.Analyzers", "build", "DDDToolkit.Analyzers.targets");
        var project = Path.Combine(_project, "Ordering.Domain.proj");

        // The two targets the step names as its neighbours, which the SDK brings; empty, since nothing else of a build
        // is needed to decide whether a module is declared and what is written.
        File.WriteAllText(
            project,
            $"""
            <Project>
              <PropertyGroup>
                <Language>C#</Language>
                <IntermediateOutputPath>obj\</IntermediateOutputPath>
                {string.Concat(properties.Select(property => $"<{property.Key}>{Escaped(property.Value)}</{property.Key}>"))}
              </PropertyGroup>
              <Import Project="{Escaped(targets)}" />
              <Target Name="PrepareForBuild" />
              <Target Name="CoreCompile" />
            </Project>
            """);

        var (exitCode, output) = await RunAsync("msbuild", project, "-t:CoreCompile", "-getItem:" + itemType, "-nologo", "-nodeReuse:false", "-noAutoResponse");
        exitCode.Should().Be(0, output);

        return JsonDocument.Parse(output).RootElement.GetProperty("Items").TryGetProperty(itemType, out var items)
            ? [.. items.EnumerateArray().Select(item => item.Clone())]
            : [];
    }

    private async Task<(int ExitCode, string Output)> RunAsync(params string[] arguments)
    {
        var start = new ProcessStartInfo(DotnetHost())
        {
            WorkingDirectory = _project,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };

        foreach (var argument in arguments)
        {
            start.ArgumentList.Add(argument);
        }

        // The build's own MSBuild, not the one that built this test run.
        foreach (var inherited in (string[])["MSBUILD_EXE_PATH", "MSBuildExtensionsPath", "MSBuildSDKsPath", "MSBuildLoadMicrosoftTargetsReadOnly"])
        {
            start.Environment.Remove(inherited);
        }

        start.Environment["DOTNET_CLI_TELEMETRY_OPTOUT"] = "1";
        start.Environment["DOTNET_NOLOGO"] = "1";

        using var process = Process.Start(start)!;
        var output = process.StandardOutput.ReadToEndAsync(TestContext.Current.CancellationToken);
        var error = process.StandardError.ReadToEndAsync(TestContext.Current.CancellationToken);

        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(TestContext.Current.CancellationToken);
        timeout.CancelAfter(TimeSpan.FromMinutes(2));
        try
        {
            await process.WaitForExitAsync(timeout.Token);
        }
        catch (OperationCanceledException)
        {
            process.Kill(entireProcessTree: true);
            throw;
        }

        return (process.ExitCode, await output + await error);
    }

    /// <summary>The dotnet that runs this test.</summary>
    private static string DotnetHost()
    {
        if (Environment.GetEnvironmentVariable("DOTNET_HOST_PATH") is { Length: > 0 } host && File.Exists(host))
        {
            return host;
        }

        if (Environment.ProcessPath is { } process && string.Equals(Path.GetFileNameWithoutExtension(process), "dotnet", StringComparison.OrdinalIgnoreCase))
        {
            return process;
        }

        var executable = OperatingSystem.IsWindows() ? "dotnet.exe" : "dotnet";
        if (Environment.GetEnvironmentVariable("DOTNET_ROOT") is { Length: > 0 } root && File.Exists(Path.Combine(root, executable)))
        {
            return Path.Combine(root, executable);
        }

        return "dotnet";
    }

    /// <summary>Text as MSBuild reads it back unchanged inside an XML project: its own special characters escaped, then XML's.</summary>
    private static string Escaped(string text)
        => System.Security.SecurityElement.Escape(text
            .Replace("%", "%25", StringComparison.Ordinal)
            .Replace("$", "%24", StringComparison.Ordinal)
            .Replace("@", "%40", StringComparison.Ordinal)
            .Replace(";", "%3B", StringComparison.Ordinal))!;

    private static string RepositoryRoot()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, "DDDToolkit.slnx")))
            {
                return directory.FullName;
            }
        }

        throw new DirectoryNotFoundException($"No DDDToolkit.slnx above '{AppContext.BaseDirectory}'.");
    }
}
