using DDDToolkit.Analyzers.Tests.Harness;
using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace DDDToolkit.Analyzers.Tests.Integrations;

/// <summary>
/// The design-time factory the build writes beside a context marked <c>[SupabaseMigrations]</c>: on Npgsql, pointing
/// nowhere, with <c>UseDDDToolkitDesignTime()</c>, in the context's own assembly, where <c>dotnet ef</c> looks for it.
/// A factory of the project's own wins; a context no factory can be written for, and that has none, is DDD00031.
/// </summary>
public sealed class SupabaseDesignTimeFactoryGeneratorTests
{
    private const string OrderingContext = """
        using DDDToolkit.EntityFramework.Supabase;
        using Microsoft.EntityFrameworkCore;

        [assembly: DDDToolkit.Abstractions.Attributes.Module("Ordering")]

        namespace Shop.Ordering;

        [SupabaseMigrations]
        public sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options);
        """;

    /// <summary>The module's project: the toolkit's Entity Framework integration, the Supabase package and Npgsql's provider.</summary>
    private static GeneratorTestHost Module(string source)
        => GeneratorTestHost.Create(source).WithAssemblyName("Shop.Ordering").WithEntityFrameworkRuntime().WithSupabase().WithNpgsql();

    [Fact]
    public void A_marked_context_gets_a_design_time_factory_beside_it()
    {
        var result = Module(OrderingContext).Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.ShouldHaveGenerated("Shop.Ordering.OrderingContextDesignTimeFactory.g.cs");
        var factory = result.Source("OrderingContextDesignTimeFactory");
        factory.Should().Contain("namespace Shop.Ordering;")
            .And.Contain("public sealed class OrderingContextDesignTimeFactory : global::Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<global::Shop.Ordering.OrderingContext>")
            .And.Contain("public global::Shop.Ordering.OrderingContext CreateDbContext(string[] args)")
            .And.Contain(
                "=> new global::Shop.Ordering.OrderingContext(global::DDDToolkit.EntityFramework.DependencyInjection.UseDDDToolkitDesignTime("
                + "global::Microsoft.EntityFrameworkCore.NpgsqlDbContextOptionsBuilderExtensions.UseNpgsql("
                + "new global::Microsoft.EntityFrameworkCore.DbContextOptionsBuilder<global::Shop.Ordering.OrderingContext>(), \"Host=unused\")).Options);",
                "the factory builds the context on Postgres, pointing nowhere, with the history where the host's UseDDDToolkit keeps it");
        factory.Should().StartWith("// <auto-generated/>").And.NotContain("\r");

        // What dotnet ef sees in the assembly: one class it can make the context through.
        var made = result.OutputCompilation.GetTypeByMetadataName("Shop.Ordering.OrderingContextDesignTimeFactory")!;
        made.AllInterfaces.Should().ContainSingle(implemented => implemented.ToDisplayString() == "Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<Shop.Ordering.OrderingContext>");
        made.InstanceConstructors.Should().ContainSingle(constructor => constructor.Parameters.Length == 0 && constructor.DeclaredAccessibility == Accessibility.Public);
    }

    [Fact]
    public void The_written_factory_makes_the_context_on_Npgsql_with_its_history_in_the_contexts_schema()
    {
        // Run, not read. An application, so the one assembly the test loads holds the context and its factory.
        var emitted = Module("""
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;

            namespace Shop.Ordering;

            [SupabaseMigrations]
            public sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options)
            {
                protected override void OnModelCreating(ModelBuilder modelBuilder) => modelBuilder.HasDefaultSchema("ordering");
            }
            """).AsApplication().Run(GeneratorTestHost.SupabaseGenerators()).Emit();

        var factory = emitted.New("Shop.Ordering.OrderingContextDesignTimeFactory");
        using var context = (Microsoft.EntityFrameworkCore.DbContext)emitted.Call(factory, "CreateDbContext", (object)Array.Empty<string>())!;

        context.GetType().FullName.Should().Be("Shop.Ordering.OrderingContext");
        context.Database.ProviderName.Should().Be("Npgsql.EntityFrameworkCore.PostgreSQL", "the Supabase export is always Postgres");
        Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService<Microsoft.EntityFrameworkCore.Migrations.IHistoryRepository>(context)
            .GetInsertScript(new Microsoft.EntityFrameworkCore.Migrations.HistoryRow("20260101000000_Probe", "10.0.0"))
            .Should().Contain("INSERT INTO ordering.\"__EFMigrationsHistory\"", "the history is where a host that wires the context with UseDDDToolkit reads it");
    }

    [Fact]
    public void The_written_factory_is_not_held_to_DDD00074_and_would_pass_it()
    {
        // The factory calls UseDDDToolkitDesignTime(), so the analyzer that holds a factory written by hand to it has
        // nothing to say; and it reads no generated code besides, so it never sees this one.
        var result = Module(OrderingContext)
            .WithAnalyzers(GeneratorTestHost.EntityFrameworkAnalyzers())
            .Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.AnalyzerDiagnostics.Should().NotContain(diagnostic => diagnostic.Id == "DDD00074");

        // A factory written by hand without the call, beside an unmarked context, is still reported: the analyzer
        // stays what it was.
        var byHand = Module("""
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Design;

            namespace Shop.Ordering;

            public sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options);

            public sealed class OrderingContextFactory : IDesignTimeDbContextFactory<OrderingContext>
            {
                public OrderingContext CreateDbContext(string[] args) => new(new DbContextOptionsBuilder<OrderingContext>().UseNpgsql("Host=unused").Options);
            }
            """)
            .WithAnalyzers(GeneratorTestHost.EntityFrameworkAnalyzers())
            .Run(GeneratorTestHost.SupabaseGenerators());

        byHand.AnalyzerDiagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "DDD00074");
    }

    [Fact]
    public void Without_the_toolkits_Entity_Framework_the_factory_leaves_the_history_where_Entity_Framework_keeps_it()
    {
        // A project that does not reference DDDToolkit.EntityFramework has a context the toolkit does not wire, as
        // DDD00074 reads it: its history is where Entity Framework keeps it, in the host and in the factory alike.
        var result = GeneratorTestHost.Create(OrderingContext).WithAssemblyName("Shop.Ordering").WithSupabase().WithNpgsql()
            .Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.ShouldContain(
            "OrderingContextDesignTimeFactory",
            "=> new global::Shop.Ordering.OrderingContext(global::Microsoft.EntityFrameworkCore.NpgsqlDbContextOptionsBuilderExtensions.UseNpgsql("
            + "new global::Microsoft.EntityFrameworkCore.DbContextOptionsBuilder<global::Shop.Ordering.OrderingContext>(), \"Host=unused\").Options);");
        result.ShouldNotContain("OrderingContextDesignTimeFactory", "UseDDDToolkitDesignTime");
    }

    [Theory]
    [InlineData("public sealed class OrderingContextFactory : IDesignTimeDbContextFactory<OrderingContext>")]
    [InlineData("internal sealed class ByAnotherName : IDesignTimeDbContextFactory<OrderingContext>")]
    [InlineData("public sealed record OrderingContextFactory : IDesignTimeDbContextFactory<OrderingContext>")]
    public void A_factory_of_the_projects_own_wins_and_nothing_is_written_or_said(string declaration)
    {
        // The project's own, whatever it is called and however it builds the context: dotnet ef takes it, and so does an
        // export in this project. An export or a check in another project needs it public, with a public parameterless
        // constructor, and the exporting project says so where it runs (SupabaseMigrationsGeneratorTests). Here it even
        // builds the context without the options alone, which no written factory could.
        var result = Module($$"""
            using DDDToolkit.EntityFramework;
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Design;

            namespace Shop.Ordering;

            [SupabaseMigrations]
            public sealed class OrderingContext(DbContextOptions<OrderingContext> options, string schema) : DbContext(options);

            {{declaration}}
            {
                public OrderingContext CreateDbContext(string[] args)
                    => new(new DbContextOptionsBuilder<OrderingContext>().UseNpgsql("Host=unused").UseDDDToolkitDesignTime().Options, "ordering");
            }
            """).Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.ShouldNotHaveDiagnostic("DDD00031");
        result.GeneratedSources.Should().NotContain(source => source.HintName.Contains("DesignTimeFactory", StringComparison.Ordinal));
    }

    [Fact]
    public void A_factory_of_the_projects_own_that_makes_two_contexts_wins_for_both()
    {
        // dotnet ef takes every context a factory makes; a second factory beside one of them would make the startup
        // project's list of contexts hold it twice, which dotnet ef refuses.
        var result = Module("""
            using DDDToolkit.EntityFramework;
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Design;

            namespace Shop.Ordering;

            [SupabaseMigrations]
            public sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options);

            [SupabaseMigrations]
            public sealed class ShippingContext(DbContextOptions<ShippingContext> options) : DbContext(options);

            public sealed class ShopFactory : IDesignTimeDbContextFactory<OrderingContext>, IDesignTimeDbContextFactory<ShippingContext>
            {
                OrderingContext IDesignTimeDbContextFactory<OrderingContext>.CreateDbContext(string[] args)
                    => new(new DbContextOptionsBuilder<OrderingContext>().UseNpgsql("Host=own").UseDDDToolkitDesignTime().Options);

                ShippingContext IDesignTimeDbContextFactory<ShippingContext>.CreateDbContext(string[] args)
                    => new(new DbContextOptionsBuilder<ShippingContext>().UseNpgsql("Host=own").UseDDDToolkitDesignTime().Options);
            }
            """).Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.ShouldNotHaveDiagnostic("DDD00031");
        result.GeneratedSources.Should().NotContain(source => source.HintName.Contains("DesignTimeFactory", StringComparison.Ordinal), "the second context is the factory's as much as the first");
    }

    [Theory]
    [InlineData("public sealed class OrderingContext(DbContextOptions<OrderingContext> options, string? schema = null) : DbContext(options);")]
    [InlineData("public sealed class OrderingContext(DbContextOptions<OrderingContext> options, params string[] schemas) : DbContext(options);")]
    [InlineData("""
        public sealed class OrderingContext : DbContext
        {
            [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
            public OrderingContext(DbContextOptions<OrderingContext> options) : base(options) => Schema = "ordering";

            public required string Schema { get; init; }
        }
        """)]
    public void A_context_made_with_its_options_alone_gets_a_factory_whatever_else_its_constructor_may_take(string declaration)
    {
        // new OrderingContext(options) compiles for each of these, so the build writes it.
        var result = Module($$"""
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;

            namespace Shop.Ordering;

            [SupabaseMigrations]
            {{declaration}}
            """).Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.ShouldNotHaveDiagnostic("DDD00031");
        result.ShouldHaveGenerated("Shop.Ordering.OrderingContextDesignTimeFactory.g.cs");
    }

    [Fact]
    public void A_factory_dotnet_ef_would_not_use_does_not_keep_the_build_from_writing_one()
    {
        // An abstract factory, and one for another context: neither makes this context, so the build writes its own.
        var result = Module("""
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Design;

            namespace Shop.Ordering;

            [SupabaseMigrations]
            public sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options);

            public sealed class ReportingContext(DbContextOptions<ReportingContext> options) : DbContext(options);

            public abstract class FactoryBase : IDesignTimeDbContextFactory<OrderingContext>
            {
                public abstract OrderingContext CreateDbContext(string[] args);
            }

            public sealed class ReportingContextFactory : IDesignTimeDbContextFactory<ReportingContext>
            {
                public ReportingContext CreateDbContext(string[] args) => new(new DbContextOptionsBuilder<ReportingContext>().Options);
            }
            """).Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.ShouldHaveGenerated("OrderingContextDesignTimeFactory");
        result.ShouldNotContain("OrderingContextDesignTimeFactory", "ReportingContext");
    }

    [Fact]
    public void An_unmarked_context_gets_no_factory()
    {
        var result = Module(OrderingContext.Replace("[SupabaseMigrations]", string.Empty, StringComparison.Ordinal))
            .Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.GeneratedSources.Should().NotContain(source => source.HintName.Contains("DesignTimeFactory", StringComparison.Ordinal), "the marker is what the factory is written from");
    }

    [Fact]
    public void An_internal_context_gets_an_internal_factory_and_a_nested_one_a_factory_named_after_both()
    {
        var result = Module("""
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;

            namespace Shop.Ordering;

            [SupabaseMigrations]
            internal sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options);

            public static class Reporting
            {
                [SupabaseMigrations]
                public sealed class Context(DbContextOptions<Context> options) : DbContext(options);
            }
            """).Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.ShouldContain("OrderingContextDesignTimeFactory", "internal sealed class OrderingContextDesignTimeFactory");
        result.ShouldContain(
            "ReportingContextDesignTimeFactory",
            "public sealed class ReportingContextDesignTimeFactory : global::Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<global::Shop.Ordering.Reporting.Context>");
    }

    [Theory]
    [InlineData(
        "public sealed class OrderingContext(DbContextOptions<OrderingContext> options, string schema) : DbContext(options);",
        "has no constructor that takes its options alone, DbContextOptions<OrderingContext>, which the design-time factory the build writes makes it with, and no factory of its own beside it")]
    [InlineData(
        "public abstract class OrderingContext(DbContextOptions options) : DbContext(options);",
        "it is abstract, so no design-time factory can make it")]
    [InlineData(
        "public sealed class OrderingContext<TTenant>(DbContextOptions<OrderingContext<TTenant>> options) : DbContext(options);",
        "it is generic, and the build would not know what to close it with")]
    [InlineData(
        "public sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options) { public required string Schema { get; init; } }",
        "it has required members, Schema, which the design-time factory the build writes cannot set, since no constructor that takes its options alone says it sets them with [SetsRequiredMembers]")]
    public void A_context_the_build_cannot_write_a_factory_for_is_DDD00031_at_the_context(string declaration, string reason)
    {
        var result = Module($$"""
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;

            namespace Shop.Ordering;

            [SupabaseMigrations]
            {{declaration}}
            """).Run(GeneratorTestHost.SupabaseGenerators());

        var reported = result.ShouldHaveDiagnostic("DDD00031", at: "OrderingContext");
        reported.Severity.Should().Be(DiagnosticSeverity.Error, "a module whose migrations never reach Supabase is found by the build, not by a deployment");
        reported.GetMessage().Should().StartWith("'Shop.Ordering.OrderingContext").And.Contain(reason).And.EndWith("so its migrations are not exported");
        result.GeneratedSources.Should().NotContain(source => source.HintName.Contains("DesignTimeFactory", StringComparison.Ordinal));
    }

    [Fact]
    public void A_context_whose_project_has_no_npgsql_is_DDD00031_naming_the_package()
    {
        var result = GeneratorTestHost.Create(OrderingContext).WithAssemblyName("Shop.Ordering").WithEntityFrameworkRuntime().WithSupabase()
            .Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldHaveDiagnostic("DDD00031", at: "OrderingContext").GetMessage().Should().Be(
            "'Shop.Ordering.OrderingContext' is marked [SupabaseMigrations] but its project does not reference Npgsql.EntityFrameworkCore.PostgreSQL, "
            + "which the design-time factory the build writes builds it on, and it has no factory of its own beside it, so its migrations are not exported");
    }

    [Fact]
    public void An_edit_that_changes_no_context_and_no_factory_writes_nothing_anew()
    {
        var first = Module(OrderingContext).Run(GeneratorTestHost.SupabaseGenerators());
        first.ShouldCompile();

        var second = first.RunAgain(static (compilation, parseOptions) => compilation.AddSyntaxTrees(
            Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText("namespace Shop.Ordering;\n\ninternal sealed class Unrelated : System.IDisposable { public void Dispose() { } }", parseOptions, "Unrelated.cs")));

        second.ShouldContain("OrderingContextDesignTimeFactory", "public sealed class OrderingContextDesignTimeFactory");
        second.Driver.GetRunResult().Results
            .Single(result => result.Generator.GetGeneratorType() == typeof(DDDToolkit.EntityFramework.Supabase.Analyzers.SupabaseDesignTimeFactoryGenerator))
            .TrackedOutputSteps.SelectMany(step => step.Value).SelectMany(run => run.Outputs).Select(output => output.Reason)
            .Should().NotBeEmpty("the driver must be tracking steps, or this means nothing")
            .And.OnlyContain(reason => reason == IncrementalStepRunReason.Cached || reason == IncrementalStepRunReason.Unchanged, "a class with a base list that makes no context changes nothing written");
    }

    [Fact]
    public void A_marked_factory_is_left_to_the_list_as_before()
    {
        // The marker on a factory, as 3.1 had it: the factory is the project's own, so nothing is written beside it.
        var result = Module("""
            using DDDToolkit.EntityFramework;
            using DDDToolkit.EntityFramework.Supabase;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Design;

            namespace Shop.Ordering;

            public sealed class OrderingContext(DbContextOptions<OrderingContext> options) : DbContext(options);

            [SupabaseMigrations]
            public sealed class OrderingContextFactory : IDesignTimeDbContextFactory<OrderingContext>
            {
                public OrderingContext CreateDbContext(string[] args) => new(new DbContextOptionsBuilder<OrderingContext>().UseNpgsql("Host=unused").UseDDDToolkitDesignTime().Options);
            }
            """).Run(GeneratorTestHost.SupabaseGenerators());

        result.ShouldCompile();
        result.GeneratedSources.Should().BeEmpty("a library gets no list, and a marked factory no second factory");
    }
}
