// <auto-generated />
using System;
using System.Collections.Generic;
using Examples.Tenancy.Projects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Examples.Tenancy.Projects.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectsContext))]
    partial class ProjectsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("DDDToolkit:RequiresContextPart:tenancy.save-check", "DDDToolkit.Supporting.Tenancy.EntityFramework.TenancySaveInterceptor\nservices.AddTenancy<…, TContext>(…) of DDDToolkit.Supporting.Tenancy.EntityFramework\noptions.UseTenancy(serviceProvider)")
                .HasAnnotation("DDDToolkit:Tenancy:ReadFunctions", true)
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DDDToolkit.EntityFramework.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("ProjectsOutboxMessages", "projects");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.OrganizationUnitPath<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId>", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("AncestorId");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid")
                        .HasColumnName("DescendantId");

                    b.Property<int>("Distance")
                        .HasColumnType("integer")
                        .HasColumnName("Distance");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.ToTable((string)null);

                    b.ToFunction("tenant_unit_paths");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.OrganizationUnitRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ParentId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.ToTable((string)null);

                    b.ToFunction("tenant_units");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.PlacementRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId>", b =>
                {
                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPrimary");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("SeatId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("UnitId");

                    b.ToTable((string)null);

                    b.ToFunction("tenant_placements");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.RoleRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.RoleId>", b =>
                {
                    b.Property<string>("FromPack")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("FromPack");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.PrimitiveCollection<string[]>("Keys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Keys");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.ToTable((string)null);

                    b.ToFunction("tenant_roles");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.SeatRight<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Tenants.Contracts.ValueObjects.OrganizationUnitId, Examples.Tenancy.Tenants.Contracts.ValueObjects.RoleId>", b =>
                {
                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndsAt");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Key");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("SeatId");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartsAt");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("UnitId");

                    b.ToTable((string)null);

                    b.ToFunction("caller_rights");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.Access.SeatRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.TenantId, Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.ToTable((string)null);

                    b.ToFunction("tenant_seats");

                    b.HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("DDDToolkit.Supporting.Tenancy.EntityFramework.SeatHolderRow<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId>", b =>
                {
                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("SeatId");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);

                    b.HasAnnotation("DDDToolkit:Tenancy:FunctionSchema", "tenancy");
                });

            modelBuilder.Entity("Examples.Tenancy.Projects.Domain.Aggregates.ProjectRoles.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.PrimitiveCollection<string[]>("Keys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MadeFrom")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MadeFrom")
                        .IsUnique();

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasAnnotation("DDDToolkit:RefusesAs:Code", "projects.role-name-taken")
                        .HasAnnotation("DDDToolkit:RefusesAs:Kind", "Conflict")
                        .HasAnnotation("DDDToolkit:RefusesAs:Message", "Another project role of this tenant is called {Name} already.");

                    b.ToTable("ProjectRoles", "projects");

                    b
                        .HasAnnotation("DDDToolkit:Membership:RoleOf", "Examples.Tenancy.Projects.Domain.Aggregates.Projects.Project")
                        .HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("Examples.Tenancy.Projects.Domain.Aggregates.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByIdentity")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedByKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ChangedBySeat")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByIdentity")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CreatedBySeat")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("OwnerSeatId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Planned", "Examples.Tenancy.Projects.Domain.Aggregates.Projects.Project.Planned#DateRange", b1 =>
                        {
                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("PlannedFrom");

                            b1.Property<DateOnly>("Until")
                                .HasColumnType("date")
                                .HasColumnName("PlannedUntil");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasAnnotation("DDDToolkit:RefusesAs:Code", "projects.number-taken")
                        .HasAnnotation("DDDToolkit:RefusesAs:Kind", "Conflict")
                        .HasAnnotation("DDDToolkit:RefusesAs:Message", "Another project in this tenant already has the number {Number}.");

                    b.ToTable("Projects", "projects");

                    b
                        .HasAnnotation("DDDToolkit:Membership:At", "UnitId")
                        .HasAnnotation("DDDToolkit:Membership:Members", "Crew")
                        .HasAnnotation("DDDToolkit:Membership:Owner", "OwnerSeatId")
                        .HasAnnotation("DDDToolkit:Tenancy:RecordsWhoChanged", true)
                        .HasAnnotation("DDDToolkit:Tenancy:TenantProperty", "TenantId");
                });

            modelBuilder.Entity("Examples.Tenancy.Projects.Domain.Aggregates.Projects.Project", b =>
                {
                    b.OwnsMany("Examples.Tenancy.Projects.Domain.Aggregates.Projects.Entities.CrewMember", "Crew", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AddedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("EndsAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("SeatId");

                            b1.Property<DateTime>("StartsAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProjectId", "Id");

                            b1.HasIndex("MemberId");

                            b1.ToTable("ProjectCrewMembers", "projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.OwnsMany("DDDToolkit.Supporting.Membership.MemberRole<Examples.Tenancy.Tenants.Contracts.ValueObjects.SeatId, Examples.Tenancy.Projects.Domain.Aggregates.ProjectRoles.ValueObjects.ProjectRoleId>", "Roles", b2 =>
                                {
                                    b2.Property<Guid>("ProjectId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("CrewMemberId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RoleId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("EndsAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid?>("GivenBy")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("StartsAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("ProjectId", "CrewMemberId", "RoleId");

                                    b2.ToTable("ProjectCrewRoleGrants", "projects");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectId", "CrewMemberId");
                                });

                            b1.Navigation("Roles");
                        });

                    b.Navigation("Crew");
                });
#pragma warning restore 612, 618
        }
    }
}
