using Examples.Tenancy.Inspections.Api.GraphQl;
using Examples.Hosting;
using DDDToolkit.HotChocolate;
using HotChocolate.Execution.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Examples.Tenancy.Inspections.Api.GraphQL;

/// <summary>
/// Inspections' GraphQL source schema: a schema of its own, which a gateway in the host composes with the other
/// modules' into the one schema a client sees.
/// </summary>
/// <remarks>
/// Inspections owns the inspection. The project it is of and the seat that recorded it are named by id alone
/// (<see cref="ReferencedProject"/>, <see cref="ReferencedSeat"/>): the gateway asks Projects and Tenancy for the
/// rest. To the project it adds one field of its own, the project's inspections, so the schema has no list of
/// its own at the root: a client asks a project for them. The feature's lookup, mutation, types and loaders are
/// in its own <c>GraphQL</c> folder, beside its routes; this class only puts them together.
/// </remarks>
internal static class InspectionsGraphQL
{
    /// <summary>The name the schema is registered under, and the gateway knows it by.</summary>
    public const string SourceSchemaName = "inspections";

    /// <summary>
    /// Registers the schema when the host serves GraphQL, and answers its builder; <see langword="null"/> when
    /// the host serves none.
    /// </summary>
    /// <param name="services">The host's services.</param>
    /// <param name="host">The host's decisions, among them what every module's schema gets.</param>
    public static IRequestExecutorBuilder? AddInspectionsGraphQL(this IServiceCollection services, ModuleHost host)
    {
        ArgumentNullException.ThrowIfNull(host);

        if (host.GraphQL is not { } conventions)
        {
            return null;
        }

        var schema = services
            .AddGraphQLServer(SourceSchemaName)
            // A schema a gateway composes.
            .AddSourceSchemaDefaults()
            // This schema has no node of its own and names Projects' by its node id: it writes and reads node ids,
            // without the Node interface and without a node field.
            .AddGlobalObjectIdentification(registerNodeInterface: false)
            .AddDDDToolkitTypes()
            // Generated here: the module's ids, and the ids Projects and Tenancy publish, as scalars and node ids.
            .AddInspectionsGraphQlRuntimeBindings()
            // Generated by HotChocolate, from the attribute in Module.cs: every [Query] and [Mutation] method of this
            // project as a field, with the Query and Mutation types they are fields of, every type class and its
            // fields, and the data loaders.
            .AddInspectionsTypes()
            // The one type no class declares: a record that is internal is registered by name.
            .AddObjectType<ReferencedSeat>();

        // What the host gives every module's schema: typed errors, one spelling for enum values, a scope per
        // field, and the check that the caller has a seat.
        conventions(schema);
        return schema;
    }
}
