name: NuGet Release

on:
  release:
    types: [created]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Extract Release Version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Pack
      run: |
        dotnet pack ./Source/DDDToolkit/DDDToolkit.csproj --configuration Release --output nupkgs /p:PackageVersion=${{ steps.get_version.outputs.VERSION }}
        dotnet pack ./Source/DDDToolkit.EntityFramework/DDDToolkit.EntityFramework.csproj --configuration Release --output nupkgs /p:PackageVersion=${{ steps.get_version.outputs.VERSION }}

    - name: Publish to NuGet
      run: |
        dotnet nuget push "./nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
